### ISSUE TITLE
"Initializing rosdep database...Website may be down."

### ISSUE THREAD

**Issue by darwin7788** [SteveMacenski/slam_toolbox#120]
I'm trying to pack my ROS packages through snapcraft,  I get an error saying that:
`Installing rosdep...`
`Removing suid/guid from /home/jiegong/projects/lidartrack-`
`snap/parts/lidartracklightgbm/rosdep/install/usr/bin/sudo`
`Initializing rosdep database...`
But it gives following error.
`ERROR: cannot download default sources list from: `
`https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list`
`Website may be down.`
`We would appreciate it if you created a bug report at`
`https://launchpad.net/snapcraft/+filebug with the above text included.`
And I can not access the said link from my browser, In this case what do I do, help..(on ubuntu 16.04.2 lts)

**Comment by SteveMacenski** [comment]
This is unrelated to the package. This is just a webserver / connection issue, you must be on the internet to accomplish this. 

If the server is down right now, wait a little while
