### ISSUE TITLE
Common coordinate system between remaps

### ISSUE THREAD

**Issue by precyon** [SteveMacenski/slam_toolbox#123]
Hey Steve,

I am PhD student working on SLAM and I'm beginning to use this package. This is a question/discussion and not an issue.

I reckon that in production deployments of such robots, the environment might need to be remapped frequently ( assuming no continuous lifelong mapping for now).  Since the origin of these remaps depends on where robot starts, isn't there a requirement of a common coordinate frame between these remaps?  Landmarks (like goals, application specific positions) with respect to the first map must be mapped accurately to the next.  How do you recommend that to be done? I understand there is an option to "start from dock" but small errors, particularly in heading in the pose at the dock, can create quite a bit of offset far away from the origin.  Or is this alignment between maps done manually?

**Comment by SteveMacenski** [comment]
If you check in the code, I do this for you, its call the `reprocessing_transform`. I find the transformations between the odometry frame of the mapping session and transform all the current measurements into that frame to process. That frame is found from the set initial pose and then a scan matched refinement to get a more accurate estimate of the pose in the continued map.
