### ISSUE TITLE
Need some help in implementing 2D Lidar based SLAM in Gazebo

### ISSUE THREAD

**Issue by ahar** [SteveMacenski/slam_toolbox#142]
Hello,

I have looked into your package. But somehow I can't figure out how to perform SLAM with this package. I have a simulation environment created in Gazebo. I move the robot (2D lidar mounted) in a predefined trajectory. I want to estimate its pose and develop a map of it. If you can provide some suggestion for using this package for this purpose, will be very helpful.

regards,
Anindya

**Comment by SteveMacenski** [comment]
This is a good question to direct to ROS Answers, since its not reporting a bug or feature request. 

I’ll follow up there :-)
