### ISSUE TITLE
Map not updating on tb3 ros2 setup

### ISSUE THREAD

**Issue by dhruvsam** [SteveMacenski/slam_toolbox#144]
I have a tb3 ros2 setup with the lds01 Lidar. I am running the mapping with the command - "ros2 launch slam_toolbox online_sync_launch.py", and viz it on Rviz. While I get a map when I first launch the slam toolbox, the map doesnt update as I move the bot around.

**Comment by SteveMacenski** [comment]
Any errors? Are you sure you’re on the right topic and have valid TF trees?

**Comment by SteveMacenski** [comment]
Please redirect to ros answers
