### ISSUE TITLE
New Default SLAM In ROS2: Maintainership, Process, Release, Testing, Oh My!

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/slam_toolbox#151]
Per discussions in the official ROS2 TSC Navigation working group (https://github.com/ros-planning/navigation2/issues/1389), Matt and I with input from the rest of the working group and navigation community have decided to make this project the new default ROS2 SLAM implementation to ship with ROS2 and Navigation.

As part of this, we need to create more formality in process and maintainership moving forward to make sure its not a one-man show of Steve.

On this discussion, we need the following:
- [x] Additional maintainers with expressed interest and use of SLAM Toolbox. This should include at least 1 additional company using SLAM Toolbox and a member of OSRF with administration rights in case other maintainers are needing to be added due to maintainers abandoning the project. 
- [x] Process around reviewing and merging pull requests and issue tickets
- [x] Process or consistency around the release cycles and careful not to break API or functionality after a distribution has been released
- [ ] Adding additional testing capabilities for units and integration to increase the reliability of PRs behind builds and checking some basic math. 
- [x] Create tutorials and additional documentation about use and examples in navigation. Replace Cartographer references with ST
- [x] link to slam tutorial on navigation2
- [x] Lint for ROS2 styling
  - [x] uncrustify
  - [x] cpplint
  - [x] cppcheck
  - [x] xmllint
  - [x] pep / etc that shouldnt be an issue for a c++ lib
  - [x] flake8
  - [x] cmake lint (skipping, there were just an insane number of warnings from low-level cmake that aren't worth the bandwidth to resolve. I resolved all higher-level and actual errors.)
- [x] issue and pr templates
- [ ] finish porting with interactive markers and rviz plugin (#177 covers)

**Comment by LeroyR** [comment]
Consider to Split the package into e.g. msg and viz.

This enables just using messages (or rviz) from other hosts without building the code or not building the rviz plugins for hosts without display.

**Comment by SteveMacenski** [comment]
PRs always appreciated :-)

**Comment by LeroyR** [comment]
I could try, but would do it on the melodic branch if thats ok?

**Comment by SteveMacenski** [comment]
Closing, opened a ticket for the remaining ROS2 work, but its no longer motivational on this higher level task.

**Comment by alikureishy** [comment]
> Closing, opened a ticket for the remaining ROS2 work, but its no longer motivational on this higher level task.

@SteveMacenski Would you mind posting the new ticket(s) so viewers could follow along this trail?
