### ISSUE TITLE
Where is the /initial_pose topic?

### ISSUE THREAD

**Issue by Rayman** [SteveMacenski/slam_toolbox#156]
Hey,

Thank you for this wonderful package.

I've read in the documentation that there should be a `/initial_pose` topic to minimize the amount of changes required for moving to this mode over AMCL. I could not find this topic it and I've also looked through the code.

Is this a feature that is still a TODO? Is this something that you would accept a PR on?

**Comment by SteveMacenski** [comment]
Its been in the localization node since its inception. Check there.

**Comment by SteveMacenski** [comment]
See [here](https://github.com/SteveMacenski/slam_toolbox/blob/eloquent-devel/src/slam_toolbox_localization.cpp#L30)
