### ISSUE TITLE
Quantitative Analysis of Localization Performance

### ISSUE THREAD

**Issue by darius-lim2016** [SteveMacenski/slam_toolbox#170]
Hi,

Thanks for your outstanding package. I have tested this package for my FYP, the outcome of this package is really good. When I tested this package in a real robot in localization mode, sometime, the robot would lost in the map maybe due to inaccuracy of the odometer.  While in localization mode, is there a parameter or rostopic to tell the robot that it has lost? Something like localization metric to justify how good or how bad the localization?

Now, to identify lost, rviz is used to check the scan matching with respect to the map.

Hope you can enlighten me. Thanks.

Darius

**Comment by SteveMacenski** [comment]
Hi,

thanks for using it and the nice words!

Right now there is no localization quality rating. That is something, however, I would merge if you submitted a PR. The scan matcher will report a scoring of the quality of the match, that may be useful as a starting point to computing a metric. Alternatively, you could take the scan and try to match it against the map itself as a "new capability" and compute a more traditional score. A third thing you may be able to leverage is the relative motion. If the robot jumps in a direction it can't possibly move (over a threshold) or too far of a distance, you could use that to detect delocalization.

Steve
