### ISSUE TITLE
Suitable for visual slam?

### ISSUE THREAD

**Issue by jsseng** [SteveMacenski/slam_toolbox#172]
Hi, I was just looking over SLAM toolbox and I was wondering your thoughts on if it might work in this scenario.  I have a neural network that outputs the driveable space boundary:

https://www.youtube.com/watch?v=x2nGruHfDy8&feature=youtu.be

If I could map the pixels to 3-d space, then I could convert this to a ROS LaserScan message.  Any thoughts on if you think this might work with SLAM toolbox?  Thanks!

**Comment by SteveMacenski** [comment]
No idea, but doesn't sound too hard to try out

**Comment by jsseng** [comment]
Okay, thanks for the input.  I'll give it a shot.

**Comment by nickvaras** [comment]
Interesting. Please let us know how that works for you if possible!
