### ISSUE TITLE
Localization failed when lidar fov changed

### ISSUE THREAD

**Issue by zhangli921** [SteveMacenski/slam_toolbox#179]
**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 Eloquent
- Version or commit hash:
  - 

#### Steps to reproduce issue

1. Mapping with lidar range 180 degrees, then serialize the map.
![180-lidar-range](https://user-images.githubusercontent.com/55520454/76207827-77c0bf80-6239-11ea-88c8-f95df10bb363.png)
![serialize-map](https://user-images.githubusercontent.com/55520454/76207875-8dce8000-6239-11ea-8a83-0ce997952957.png)

2. Change the lidar range to 360 degrees. 
![360-lidar-range](https://user-images.githubusercontent.com/55520454/76207897-9757e800-6239-11ea-8b8c-d8f446cd8e7a.png)

3. Deserialize the map in Localization mode.
![localization-failed](https://user-images.githubusercontent.com/55520454/76207912-a179e680-6239-11ea-8e4b-90e895d9614b.png)

#### Expected behavior
All things goes well.
#### Actual behavior
Localization failed.

**Comment by SteveMacenski** [comment]
That would be correct. It is not permissible to arbitrarily change the laser characteristics as these are static hardware capabilities. That simulation isn’t practical. You’re fundamentally modifying how information is encoded and projected. 

No form of graph slam will handle this. I’ve spent some time on the multirobot branch to enable things like this, but its incomplete. 

If some documentation in the readme that this only allows for serialization/deserialization of homogeneous lidar systems, I’d accept a PR on it.
