### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by Leonti** [SteveMacenski/slam_toolbox#181]
#### Feature description
Currently when tyring to install slam-toolbox via apt, there is only `ros-dashing-slam-toolbox` package:
http://packages.ros.org/ros2/ubuntu/dists/bionic/main/binary-armhf/Packages

Would it be possible to release `ros-eloquent-slam-toolbox` package for Eloquent?

Thanks!

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/23959

It’ll be available in the next sync. I released it last week.
