### ISSUE TITLE
merge map, rotation

### ISSUE THREAD

**Issue by sunrentao** [SteveMacenski/slam_toolbox#193]
- Operating System:
  - Ubuntu 18.04
- Installation type:
   -  from source 
- ROS Version
  - ROS1
- Version or commit hash:
  -9fd560ab1f56187e2a4397c8a9440da9b2dfa8c1

#### Steps to reproduce issue
Launch merge_maps_kinematic.launch 
Add 2 submaps and manipulate one of them to merge 

#### Expected behavior

generate a map as indicated

#### Actual behavior

generate a wrong map, problem happens about rotation

#### Additional information

also another problem is that for example if I call rosservice merge_map twice, the map will make another transformation respect to last position

**Comment by SteveMacenski** [comment]
> generate a wrong map, problem happens about rotation

Is not a helpful description. Please add detail and examples.

**Comment by sunrentao** [comment]
![rviz_screenshot_2020_04_03-11_25_42](https://user-images.githubusercontent.com/19492452/78345737-559f3080-759e-11ea-8580-d53165bb2097.png)

hello, for example, this is the first step to add submap, then , if I rotate this map, then the generated map is as following, 

![rviz_screenshot_2020_04_03-11_26_16](https://user-images.githubusercontent.com/19492452/78345872-87b09280-759e-11ea-8cd1-f970172eb3cf.png)

and if I only move the map without rotation, first time generated map will be ok, but if I generate map twice without any moving , it will be like this 

![rviz_screenshot_2020_04_03-11_28_24](https://user-images.githubusercontent.com/19492452/78346017-bd557b80-759e-11ea-8f31-bc6f3be30607.png)

I read the code, that every time the map tool give a new data, it will update "submap_marker_transform_" with " previous_submap_correction.inverse() " I think this is the problem, but I am not sure.

**Comment by SteveMacenski** [comment]
I did not consider trying to hit the merge button multiple times as if you merge your N maps, you should be done. 

However a PR would be appreciated that resolves your issue.
