### ISSUE TITLE
the differece with cartographer

### ISSUE THREAD

**Issue by xbcdbc** [SteveMacenski/slam_toolbox#197]
Does the package is similar to cartographer?Include the localization mode,is also similar to the cartographer's pure_localization?

**Comment by SteveMacenski** [comment]
Please read the readme file and ask any questions on ROS Answers.

**Comment by xbcdbc** [comment]
Thank you the perfect code. I have read the code,the front-end is similar to cartographer:"corelative scan match algorithm and scan-to-submap strategy", the back-end is different, the carto is create constraints by submap, and slam tool_box is scan-to-scan,Is that right?

**Comment by xbcdbc** [comment]
For the map quality，do you compare with the gmapping and cartographer ？
