### ISSUE TITLE
VSLAM

### ISSUE THREAD

**Issue by charlotteheggem** [SteveMacenski/slam_toolbox#200]
Hi Steve,

We are working on a mobile robot running ROS2 Eloquent with 2 x SICK laser scanners and 3 x Realsense D435 cameras and would like to use slam_toolbox for (visual)SLAM. You mentioned cameras as an input source for SLAM in your talk on ROSCON 2019, but it does not seem like it an option to set images or 3D data as input in the slam_toolbox. 

1. Does slam_toolbox support cameras as input?  If not; is there an way to use the data from cameras as input? Similar to the way cartographer can be configured to use 3D lidar data?
2. How can slam_toolbox be configured for multiple laser scanners? From the issues it seems that the package provide support for multiple lasers.

Best regards

**Comment by SteveMacenski** [comment]
I did not mention that this project is able to process visual data. If you would like a visual slam solution, I suggest asking on ROS Answers. 

As for multi-scanner, there’s an open ticket and branch working on that. If that’s something you’re sufficiently motivated to help finish, I can give you a run down on its current state.
