### ISSUE TITLE
ROS2 Map Saver Executable Not Found

### ISSUE THREAD

**Issue by Michael-Equi** [SteveMacenski/slam_toolbox#216]
- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Source
- ROS Version
  - ROS2
- Version or commit hash:
  - 3dee86162074a9df862016cfb32043f4b03ff4f1

#### Steps to reproduce issue
Clone slam_toolbox into navigation folder along with ROS2 navigation2. Clone all dependencies with vcs import into the same folder. This results in a workspace folder with navigation2, slam_toolbox, and all dependencies. Colcon build the entire workspace and source the install script. Ros2 launch the tutlebot3 simulator and the slam_toolbox asynchronous mapper. Attempting to call the service /map_saver results in being logged and no map being saved.

```
[async_slam_toolbox_node-1] [INFO] [1593970382.079435327] [slam_toolbox]: SlamToolbox: Saving map as map.
[async_slam_toolbox_node-1] No executable found 
```

#### Expected behavior
The map should be saved to the path that is sent over in the service.

#### Actual behavior
Cannot find the executable required to call the function.

#### Additional information
Looking at the source code it looks like a problem here 

```
  const std::string name = req->name.data;
  if (name != "") {
    RCLCPP_INFO(node_->get_logger(),
      "SlamToolbox: Saving map as %s.", name.c_str());
    int rc = system(("ros2 run nav2_map_server map_saver -f " + name).c_str());
  } else {
    RCLCPP_INFO(node_->get_logger(),
      "SlamToolbox: Saving map in current directory.");
    int rc = system("ros2 run nav2_map_server map_saver");
  }
```

as nav2_map_server map_saver is not a valid executable in the nav2_map_server package. The only options are map_saver_cli,    map_saver_server, and  map_server.

**Comment by SteveMacenski** [comment]
What version of ROS are you using (Eloquent, Dashing, Foxy, ...), and have you actually installed nav2_map_server? 

You're right, I believe we did change some names. Can you submit a PR to resolve?
