### ISSUE TITLE
Different base_frame defaults for online and offline mapping

### ISSUE THREAD

**Issue by NikolasE** [SteveMacenski/slam_toolbox#217]
Frames in configs should be consistent (and there is a lot of shared params in the files, so it's hard to see which variables change between the different modes)

#### Actual behavior
no suprises when switching between online and offline mode

#### Additional information
mapper_params_offline.yaml:
base_frame: base_link

mapper_params_online_sync.yaml:
base_frame: base_footprint

**Comment by SteveMacenski** [comment]
Ah, I think it should be `_footprint` in all cases. Mind updating those?

**Comment by NikolasE** [comment]
I created a sophisticated PR :) [224](https://github.com/SteveMacenski/slam_toolbox/pull/224)

But I think the shared parameters should be in a base-configuration and only the changed parameter in their own files.
