### ISSUE TITLE
Hello, I wonder when will be opened for Pose Graph Merging function?

### ISSUE THREAD

**Issue by Geonhee-LEE** [SteveMacenski/slam_toolbox#222]
Hello, I'm really appreciate your contribution.
I am interested in merging the maps by mapping from each other. 
I wonder when will be opened for Pose Graph Merging function?

Thanks.
Regards.

**Comment by SteveMacenski** [comment]
I haven't been working on it and am unlikely to do so in the foreseeable future. I'm more than happy to help someone else come up with a plan and review a PR for it, but my time is limited and there hasn't been a strong desire for it. 

Closing in redundancy to #19
