### ISSUE TITLE
[ROS2] Convert nodes to lifecycle nodes

### ISSUE THREAD

**Issue by Michael-Equi** [SteveMacenski/slam_toolbox#244]
#### Feature description
I feel like there is a lot to gain in this repository by using something like a life-cycle node over the standard node interface. I haven't dug too deep into this repository yet but integrating it into my own project makes me see how it could be very useful. If this is something others are interested in and there are no objection I may be able to contribute this feature in a month or so.

**Comment by SteveMacenski** [comment]
No objections here, though all this repos launch files need to have lifecycle autotransition then. We can’t tie out of the box behavior of this to Nav2’s lifecycle manager since this will be used often outside that context.

**Comment by SteveMacenski** [comment]
Keep in mind SLAM has alot of dynamic memory allocations in it either way - so lifecycle is nice for integrating and consistency, but you wont be able to isolate the memory allocations to configuration and construction.

**Comment by SteveMacenski** [comment]
@Michael-Equi any plans still to contribute back a lifecycled-version of SLAM Toolbox?

**Comment by Michael-Equi** [comment]
Likely not any time soon, the progress I made on it can be found [here](https://github.com/BytesRobotics/slam_toolbox/tree/lifecycle_node) but I hit some problems and was not able to get past them fast enough so my team settled for a less elegant solution for the time being and I havent had the time to go back and finish it.

**Comment by kei1107** [comment]
@SteveMacenski 
I tried this issue, and created PR(#561).
I hope you will take a look when you have time.
