### ISSUE TITLE
Interactive mode for deserialized maps

### ISSUE THREAD

**Issue by Tobias-Fischer** [SteveMacenski/slam_toolbox#245]
#### Feature description

I serialized a map after running `online_sync.launch`. I would like to manually close a loop in this map after deserializing it. As far as I understand, this is currently not possible. It would be great if this could be done somehow.

**Comment by Tobias-Fischer** [comment]
The error which is thrown currently is:
`  what():  vector::_M_range_check: __n (which is 533) >= this->size() (which is 0)`

Or alternatively in localization mode that `[ERROR] [1596176922.932154679]: Interactive mode is invalid outside processing mode.`

**Comment by SteveMacenski** [comment]
PRs appreciated

**Comment by Tobias-Fischer** [comment]
Any hints on where to start with a PR?

**Comment by SteveMacenski** [comment]
#329 covers the same scope
