### ISSUE TITLE
Use SaveMap service that returns a boolean and potentially consolidate Save/Load map services

### ISSUE THREAD

**Issue by Michael-Equi** [SteveMacenski/slam_toolbox#268]
#### Feature description
The service interface used to save a map should be more like the ones found in nav2 which include a boolean response indicating if it succeeded or failed. https://github.com/ros-planning/navigation2/blob/master/nav2_msgs/srv/SaveMap.srv

Also, while going through this I am curious if there is any reason why [nav_msgs](https://github.com/ros2/common_interfaces/tree/master/nav_msgs/srv), nav2_msgs, and map_msgs all have their own variants of map handling services. It looks to me that they should be consolidated together including the SaveMap and LoadMap services from the navigation2 repository. If they were consolidated into common_msgs, they would be accessible to isolated slam tooolbox users as wells as navigation2 users while keeping things more unified. It looks like this discussion has happened to some degree before but SaveMap and Loadmap services did not get included in the mini-consolidation. https://github.com/ros2/common_interfaces/pull/86

**Comment by SteveMacenski** [comment]
This map saver is just a convenience tool. You're welcome to call the map server yourself through that interface. 

> while going through this I am curious if there is any reason why nav_msgs, nav2_msgs, and map_msgs all have their own variants of map handling services

This isn't the right venue for that discussion
