### ISSUE TITLE
Add service to get map

### ISSUE THREAD

**Issue by Michael-Equi** [SteveMacenski/slam_toolbox#275]
#### Feature description
Add a service similar to the one in nav2_map_server that allows a client to get the map upon calling a service. Such a service would require adding a service message such as `nav_msgs/srv/GetMap.srv`.

**Comment by SteveMacenski** [comment]
https://github.com/SteveMacenski/slam_toolbox/blob/foxy-devel/src/slam_toolbox_common.cpp#L189

There already is, with that exact API

**Comment by Michael-Equi** [comment]
Sorry. Didn't see it.
