### ISSUE TITLE
Ignoring obstructions within the robot's frame.

### ISSUE THREAD

**Issue by ghost** [SteveMacenski/slam_toolbox#306]
While using the `slam_toolbox` in localization mode for lidar odometry, the map generated has obstacles created from the robot's body as well.

This was an issue during the mapping mode too but I cleared those obstacles manually from the map using GIMP.

This is not possible in case of localization mode. There should be a way to provide the robot's footprint, or a minimum radius in which the laser scan ignores the obstacles to prevent the robot's own body distorting the map.

![Screenshot from 2020-10-27 18-54-58](https://user-images.githubusercontent.com/66380665/97308678-25dfaf00-1887-11eb-87a8-b4a844bbbae7.png)

This also affects the global path planner's ability to make a path to the destination.

**Comment by SteveMacenski** [comment]
You should use a robot self filter or similar to remove those points before processing them for any reason - not just SLAM.

Closing since this isn't a bug or feature for SLAM Toolbox but a configuration issue for your platform.
