### ISSUE TITLE
[Question] Lifelong mapping performance

### ISSUE THREAD

**Issue by macstepien** [SteveMacenski/slam_toolbox#309]
**Required Info:**

- Installation type: Docker
- ROS Version: ROS1 -> Melodic
- Version or commit hash: 44c9f840b01b1c9b5ed351c7d0074c641ee3e21c

Hi,
I was recently testing performance of lifelong mapping node. I used five rosbags gathered by driving our robot around the warehouse, playing them repeatedly to simulate the robot moving around for some longer period of time. Each rosbag started and finished in the same spot (so that I could use the same starting position), I used _2D Pose Estimate_ in _RViz_ to get  this initial robot position (as it wasn’t zero), which I later set in slam_toolbox config. And for tests I created a script that was playing five robags over and over. Whole procedure looked like this:

- start slam_toolbox node with previously saved map
- play rosbag
- save new map and kill slam_toolbox node

I also have to mention that we are using _RPLidar_ in our robot, which initially caused some problems - map was sometimes rotated (as described in [here](https://answers.ros.org/question/359654/what-may-be-causing-my-map-to-sometimes-rotates-180-degrees-during-operation/)). I was able to fix it by later filtering rosbags - rotating lidar messages and tf accordingly to simulate as if it was mounted with cable to front (based on [rplidar driver modification](https://github.com/allenh1/rplidar_ros/pull/20)). This seems to work fine - previously map rotations were present in all of our five rosbags, after modification that problems were gone. 

In the first test I used all default parameters (as in _mapper_params_lifelong.yaml_) - just defined _map_start_pose_, _map_file_name_, and adjusted _scan_topic_, _base_frame_. Then I left the script running for about 2 hours and 10 minutes. Resulting map with graph nodes markers:
![2h10](https://user-images.githubusercontent.com/27098844/98953105-8b28d680-24fc-11eb-8eac-7a2ddb264a9b.png)
I also checked the number of graph nodes (number of markers in _karto_graph_visualization_ message). I could see that sometimes this number decreased (also in log saw confirmation that indeed some nodes were removed). But despite removing some of the nodes, more of them still were added and it looks like the total number grows linearly. I hoped that after creating enough nodes in given area it will become saturated and growth should slow down. 
![2h10lifelonggraph](https://user-images.githubusercontent.com/27098844/98953188-a7c50e80-24fc-11eb-885b-318432d748ad.png)
I tried modifying lifelong parameters to check if I will be able to get some better clearing of graph nodes ( just wanted to see what response I can get, so that’s why changes are quite large)
```
lifelong_search_use_tree: false
lifelong_minimum_score: 0.05
lifelong_iou_match: 0.65
lifelong_node_removal_score: 0.5
lifelong_overlap_score_scale: 0.1
lifelong_constraint_multiplier: 0.01
lifelong_nearby_penalty: 0.001
lifelong_candidates_scale: 0.08
```
![2hlifelongmodified](https://user-images.githubusercontent.com/27098844/98953224-b4496700-24fc-11eb-8b58-b94c49f6d865.png)
![2hlifelongmodifiedgraph](https://user-images.githubusercontent.com/27098844/98953252-be6b6580-24fc-11eb-8fe1-bd4f4f6b1bf1.png)

Sudden drop to 0 was caused by an error during map serialization. All in all I was able to get better results (after 1 hour I got 2930 graph nodes with default parameters, 1670 after modification), but still not satisfying as growth also looked linear, just with slower rate. 

I wasn’t able to find any data of how lifelong mapping actually works, so I’m wondering if maybe there are some mistakes/potential improvements that can be made to our setup or parameters. I know that right now it is a highly experimental feature, but I wanted to make sure if it isn’t just underperforming - especially if it is possible to get a cleaner map and maybe reduce growth of graph nodes. I was running these tests on docker, so I can provide the whole image or only rosbags if you would like to check it out.

**Comment by SteveMacenski** [comment]
The lifelong mapping node is clearly marked as experimental in docs, code, and launch warnings and will not receive support.
