### ISSUE TITLE
slam_toolbox on high speed robots 

### ISSUE THREAD

**Issue by cblesing** [SteveMacenski/slam_toolbox#310]
Hi, 

i'm not sure if this topic is a feature or just a question.

#### Feature description

In one of our new research projects we are dealing with high velocities up to 10 m/s. Can you give us an estimate, or have you already experienced up to what speed the toolbox still works assuming we have perfect odometry and laser readings? In my previous work and experiences with the Toolbox we only went up to 1m per second. 

best regards 
Christian

**Comment by SteveMacenski** [comment]
Direct questions to ROS Answers please.
