### ISSUE TITLE
TF issue when using sync_slam_toolbox_node

### ISSUE THREAD

**Issue by sachinkum0009** [SteveMacenski/slam_toolbox#315]
**Required Info:**

- Operating System:
  -  Ubuntu 20.04
- Installation type:
  - binaries
- ROS Version
  - ROS2, Foxy

#### Problem
I am using a mobile robot containing lidar sensor. 
When I launch the sync_slam_toolbox, it is publishing the tf from the map -> odom -> base_link.
But the links connected to the base_link are not publishing as per rviz. 
This is a weird issue. Even sometimes it says 'laser' link is not found the the tf

But when I use the tf2_tools view_frames.py The tf tree looks fine.
![Screenshot from 2020-11-28 20-38-24](https://user-images.githubusercontent.com/19277194/100779830-f2b4b080-342e-11eb-8060-79319cda53be.png)

Can you please help and even sometimes map is not publishing.

I have attached some images 
![Screenshot from 2020-11-28 20-39-19](https://user-images.githubusercontent.com/19277194/100779826-f1838380-342e-11eb-9adb-9384b92db4cc.png)

**Comment by SteveMacenski** [comment]
Ask ROS Answers, your TF issue isn't related to slam toolbox so you should not file a ticket here.
