### ISSUE TITLE
Does slam_toolbox takes into account the pitch/roll of the robot when processing scans?

### ISSUE THREAD

**Issue by pepeRossRobotics** [SteveMacenski/slam_toolbox#316]
I would like to know if this is the case. Or is if this something that could be implemented. The Idea is that if the robot is moving on uneven terrain, only scans (or part of the scans) that are at a height range are taken into account for localisation/mapping.

**Comment by SteveMacenski** [comment]
Please ask questions on ROS Answers, this is for filing bugs and features.
