### ISSUE TITLE
Compatibility with ROS Melodic

### ISSUE THREAD

**Issue by antvkov** [SteveMacenski/slam_toolbox#32]
Hi,
is slam_toolbox compatible with ROS Melodic and Ubuntu 18.04 LTS?

**Comment by SteveMacenski** [comment]
Frankly, I have no idea. This is still a project in development. I make no warranties here. The core of the library is stable for mapping but I make no promises on the localization or serialization components at this moment. 

There's nothing here that would make me think it wouldn't work with ROS Melodic. If it compiles, it'll work fine. I think Melodic changed some headers from `.h` to `.hpp` for pluginlib so with those changes it will probably compile

**Comment by SteveMacenski** [comment]
Frankly, I have no idea. This is still a project in development. I make no warranties here. The core of the library is stable for mapping but I make no promises on the localization or serialization components at this moment.
