### ISSUE TITLE
[QUESTION] Can the TBB dependency be removed？

### ISSUE THREAD

**Issue by orangetcy** [SteveMacenski/slam_toolbox#323]
branch: melodic-devel
Thanks your great work，it is really great with high performance. I want to run this project on raspberry-pi 3B+ but found  this project depend on Intel TBB. Is there any chance to remove TBB dependency or will performance decrease without TBB?

**Comment by SteveMacenski** [comment]
TBB is required for a significant scan matcher performance boost. Others have run this software on raspberry pis so I think it should be OK

**Comment by orangetcy** [comment]
Thanks for your reply. I have success to run on raspberry pi. it is really good. But I have some location float problem, maybe odom is incorrect. I will try to fix it.
Thanks again.
