### ISSUE TITLE
Analysis of Localization Performance

### ISSUE THREAD

**Issue by TZVIh** [SteveMacenski/slam_toolbox#375]
Hi,
Thank you for the amazing work you have done here.

I am looking to know what the position of the robot is and the covariance of the solution.  ( I know I can take the position from TF but I am looking for msg like amcl_pose on AMCL)

Is there a plan to put it in?

My OS is Ubuntu 18.04.5 LTS
My ROS version is ROS1

**Comment by SteveMacenski** [comment]
There are no plans for adding it, no, PRs would be accepted though
