### ISSUE TITLE
GPS Integration

### ISSUE THREAD

**Issue by nyxaria** [SteveMacenski/slam_toolbox#382]
Are there any plans of having GPS integration into the SLAM algorithm? Something like what Cartographer has, where you can simply publish gps messages onto a topic and the algorithm uses it as another data source.

Thank you for all your work!

**Comment by SteveMacenski** [comment]
No, there are no plans for that. Look at robot_localization for loosely coupled localization fusion.

**Comment by pallavbhalla** [comment]
> No, there are no plans for that. Look at robot_localization for loosely coupled localization fusion.

@SteveMacenski, does that imply that we cannot/shouldn't use another source that gives us the tf between map->odom frames (e.g. two robot_localization instances)?

**Comment by MrOCW** [comment]
@SteveMacenski @Pallav1299 Since slam_toolbox doesnt publish the pose/odom, we aren't able to fuse it into global ekf which publishes map->odom->base_link and use that odom generated?
