### ISSUE TITLE
Map merging misalignment when run multiple times in a single session

### ISSUE THREAD

**Issue by pallavbhalla** [SteveMacenski/slam_toolbox#385]
**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- ROS Version
  - ROS1
- Version or commit hash:
  - https://github.com/SteveMacenski/slam_toolbox/tree/noetic-devel
- Laser unit:
  - Hokuyo UTM-30LX laser scanner
  
#### Steps to reproduce issue

I am trying to use the map_merging feature by creating two maps from a single rosbag. Afterwards I add these submaps upon launching the map_merge_kinematic node.
The manual alignment isn't affecting the merged map.

#### Expected behavior
Map with aligned submaps.
#### Actual behavior
Map with misaligned submaps.
#### Additional information
Seems like the alignment data is being lost and the default pose is being used for merging submaps.

Not sure if I am doing something wrong. Please suggest if so.

Maps:
[submaps.zip](https://github.com/SteveMacenski/slam_toolbox/files/6376860/test.zip)

Screenshots:
submap_1:
![map_1](https://user-images.githubusercontent.com/32015105/116077506-30062d00-a6b3-11eb-9448-7395d264de44.png)

submap_2:
![map_2](https://user-images.githubusercontent.com/32015105/116077510-309ec380-a6b3-11eb-9d66-bfb8f0e2d7ab.png)

manually_aligned submaps:
![manually_aligned](https://user-images.githubusercontent.com/32015105/116077502-2e3c6980-a6b3-11eb-9092-377d0ae4f171.png)

merged submaps:
![merged](https://user-images.githubusercontent.com/32015105/116077513-31375a00-a6b3-11eb-9ab6-f572c9a561af.png)

**Comment by pallavbhalla** [comment]
Seems to be as if some transformations accumulate whenever we move the interactive markers. Aligning and merging after one action(rotation or translation), works fine. The second time, there is some offset from the given transformation(rotation or translation).
 In my case, I had to apply both rotation and translation. I will try to look into the code to find if it's actually the case.

**Comment by SteveMacenski** [comment]
Yeah, that is correct. This was built as a single-time application (assumed you'd be merging `N` maps 1 time) so I could totally believe that this doesn't reset state completely. To do so, you'd have to reset all the variables and probably also unload all of the maps since their associated markers can't really be easily zeroed out from this application

**Comment by pallavbhalla** [comment]
> To do so, you'd have to reset all the variables and probably also unload all of the maps since their associated markers can't really be easily zeroed out from this application

@SteveMacenski, Can you give more clarity about the same? 

Just to be clear, multiple actions(rotation and translation) are not supported currently in map_merging, right?
Is there a scope for improvement?

**Comment by SteveMacenski** [comment]
If you look at the code, I think it should be pretty clear - once merged nothing is reset, it just maintains state. So this was really only built to be executed 1 time per run, not multiple times. There's obviously room for improvement to make it work N times

**Comment by pallavbhalla** [comment]
> If you look at the code, I think it should be pretty clear - once merged nothing is reset, it just maintains state. So this was really only built to be executed 1 time per run, not multiple times. There's obviously room for improvement to make it work N times

Even for 1 execution per run, I witnessed that merging after a single rotation leads to misalignments in the merged map. 
@SteveMacenski, Did you face this behavior? Also, could you give some direction to the section of code where you think the problem lies?
