### ISSUE TITLE
[MacOS] Linker error when building from source

### ISSUE THREAD

**Issue by nkalupahana** [SteveMacenski/slam_toolbox#396]
**Required Info:**

- Operating System:
  - macOS 10.15
- Installation type:
  - From source
- ROS Version
  - ROS2 Foxy
- Version or commit hash:
  - Latest of foxy-devel
  
#### Steps to reproduce issue

When trying to build `slam_toolbox` from source on macOS, you get the following linker error:

```
Undefined symbols for architecture x86_64:
  "void tf2::fromMsg<geometry_msgs::msg::Quaternion_<std::__1::allocator<void> >, tf2::Quaternion>(geometry_msgs::msg::Quaternion_<std::__1::allocator<void> > const&, tf2::Quaternion&)", referenced from:
      slam_toolbox::SlamToolboxPlugin::InitialPoseCallback(std::__1::shared_ptr<geometry_msgs::msg::PoseWithCovarianceStamped_<std::__1::allocator<void> > >) in slam_toolbox_rviz_plugin.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This build was run on CI, and thus the full logs and build parameters can be viewed at https://github.com/nkalupahana/ros2-foxy-macos/runs/2699823378?check_suite_focus=true.

**Comment by SteveMacenski** [comment]
Unfortunately, I don’t offer support for MacOS, as I do not have one or access to one (or really even experience using one). I’d be happy to merge a PR resolving whatever this issue is but not something I’d plan to address.
