### ISSUE TITLE
Rotate the Pose Graph map about the origin

### ISSUE THREAD

**Issue by denesh-botsync** [SteveMacenski/slam_toolbox#413]
#### Feature description
Slam Toolbox has been an amazing implementation for our localization endeavours. Was wondering if there is a way to rotate both the .posegraph which is used for subsequent localisation and the .map which is used by the default ROS 1 move_base for planning? This is largely because it has been observed that if the map is slanted with respect to the longest corridor, the paths planned by the global planner becomes 'jagged'. However if the map is aligned to the longest corridor, the paths planned will be suitably aligned to the longest corridor as well. 

While it is possible to ensure that mapping always takes place with the robot parallel to the longest corridor is there a way to manipulate the pose graph information after a mapping session and rotate it? 

branch: noetic_devel 
local system version: Ubuntu 18.04 
ROS version on local system: ROS Noetic

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers
