### ISSUE TITLE
Slam toolbox with Visual Odometry

### ISSUE THREAD

**Issue by kushtimusPrime** [SteveMacenski/slam_toolbox#416]
Hello,
My robotics team and I want to implement the nav2 stack with a Realsense D435i. We wanted to use slam_toolbox for localization and rtabmap/rgbd_odometry for visual odometry. For slam_toolbox, we planned on using the depthimage_to_laserscan package to convert the realsense input into a scan for Slam toolbox. While running this stack, we are unable to generate a map of the environment despite having a full transform tree (map-> odom-> base_link-> camera_link-> <various camera depth, color, etc frames>). We run into the following errors shown below regarding the dropped frames. However, when we try to run rtabmap/rgbd_odometry with rtabmap localization though, we are able to generate a map. We are also able to generate a map by just running slam toolbox with a static odom -> base_link transform to complete the transform tree. Is there a better way to set this up to make slam toolbox compatible with rgbd odometry or are there better visual odometry tools that work with slam toolbox?
- Operating System:
  - Ubuntu 20.04
- Installation type:
  -  apt-get install ros-foxy-slam-toolbox
- ROS Version:
  - ROS2 foxy
- Sensor:
  - Intel Realsense D435i with ROS 2 foxy depthimage_to_laserscan package
#### Steps to reproduce issue
Run the following launch files from the following packages with base_frame configured to base_link
1. From Slam toolbox: localization.launch.py
2. From Depthimage_to_Laserscan: depthimage_to_laserscan-launch.py
3. From Rtabmap_Ros (Build from source, ROS2 branch): realsense_d400.launch.py (with the rtabmap_ros node commented out)
4. Static transform from base_link to camera_link
5. From realsense_camera: rs_launch.py
#### Expected behavior
Creates a map of the environment (/map topic is not empty)
#### Actual behavior
/map topic is empty with the following messages:
[INFO] [launch]: All log files can be found below /home/kushtimusprime/.ros/log/2021-06-25-00-41-36-760662-kushtimusprime-XPS-13-9380-77482
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [localization_slam_toolbox_node-1]: process started with pid [77484]
[localization_slam_toolbox_node-1] [INFO] [1624599697.263601718] [slam_toolbox]: Node using stack size 40000000
[localization_slam_toolbox_node-1] [INFO] [1624599697.285391432] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[localization_slam_toolbox_node-1] [INFO] [1624599697.285764797] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[localization_slam_toolbox_node-1] [INFO] [1624599698.803987092] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.764 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599698.837161163] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.797 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599698.870709130] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.831 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599698.904646026] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.864 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599698.936217126] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.897 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599698.970779940] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.930 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599699.003707781] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.963 for reason 'Unknown'
[localization_slam_toolbox_node-1] [INFO] [1624599699.036962088] [slam_toolbox]: Message Filter dropping message: frame 'camera_depth_frame' at time 1624599698.997 for reason 'Unknown'

**Comment by SteveMacenski** [comment]
This is better suited for ROS Answers
