### ISSUE TITLE
[ROS1] No more map updates after initial scan

### ISSUE THREAD

**Issue by lageorgem** [SteveMacenski/slam_toolbox#429]
Hello. I am a newbie with ROS and I want to get started using slam_toolbox. 
I am using ROS noetic on an ubuntu server on raspberry pi and I am not sure what I am missing with my configuration.

I have added this to my launch file:
```
  <node pkg="slam_toolbox" type="sync_slam_toolbox_node" name="slam_toolbox" output="screen">
    <rosparam command="load" file="$(find slam_toolbox)/config/mapper_params_offline.yaml" />
  </node>
  <node pkg="slam_toolbox" type="merge_maps_kinematic" name="merge_maps_kinematic" output="screen"/>
  <node pkg="tf" type="static_transform_publisher" name="base_to_laser_broadcaster" args="0 0 0 0 0 3.141 base_link laser_link 100" />

```

and modified the mapper_params_offline.yaml file with this config:

```
odom_frame: base_link
map_frame: map
base_frame: base_link
scan_topic: /scan
mode: mapping #localization
debug_logging: false
throttle_scans: 1
```

The LaserScan message looks correct and when I move the robot, it also moves, but the map only displays an initial scan and does not update afterwards. The estimated location and pose of the robot are also missing. Could you perhaps point me to some resources on how to get started correctly?

Thank you in advance

**Comment by SteveMacenski** [comment]
Please do not cross post with ROS answers. I’ll follow up there when I have extra cycles.
