### ISSUE TITLE
RPLidar: what does Slam Toolbox expect?

### ISSUE THREAD

**Issue by peredwardsson** [SteveMacenski/slam_toolbox#430]
**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - built from source
- ROS Version
  - ROS2 dashing
- Version or commit hash:
  - commit f57ad668a8a0199fe13cfbc54ccdfa8208599c02 (tag: 2.0.4)
- Laser unit:
  - RPLidar S1
  
#### Steps to reproduce issue
Run https://github.com/allenh1/rplidar_ros to get laser scan messages from the RP lidar. Run Slam Toolbox (in async or lifelong) and listen in on the right topic.
#### Expected behavior
Slam Toolbox maps the environment based on lidar input.
#### Actual behavior
Slam Toolbox is confused by the messages, since the number of nodes being output is a little crazy in the beginning, resulting in messages of the type 
```
[lifelong_slam_toolbox_node-9] Registering sensor: [Custom Described Lidar]
[lifelong_slam_toolbox_node-9] LaserRangeScan contains 1073 range readings, expected 918
[lifelong_slam_toolbox_node-9] LaserRangeScan contains 719 range readings, expected 918
[lifelong_slam_toolbox_node-9] LaserRangeScan contains 719 range readings, expected 918
[lifelong_slam_toolbox_node-9] LaserRangeScan contains 719 range readings, expected 918

```
The number of range reading IS weird in the beginning, so this approach does not seem appropriate for this lidar.
#### Additional information
In this particular case, we are very much interested in modifying the RPlidar code so that it works with Slam Toolbox. The problem is, we can not figure out a good way to do this. It looks like Slam Toolbox expects (n+1) range readings in the first scan, and then expects (n) range readings in the following. It seems much more appropriate that I can set up Slam Toolbox to listen to a scan and expect (n) range readings all the time, discarding such readings that are faulty. The S1 produces 720 range scans, and spins 360 degrees, meaning that one revolution returns 719 scans. Anything else is a faulty reading.

One solution which works fairly reliably is to start Slam Toolbox _after_ the RPlidar produces stable output. However, this type of micro management is asking for problems. Let's disregard this solution for now.

What does Slam Toolbox expect from RPlidar, and how can we modify either package to accomodate this?

**Comment by SteveMacenski** [comment]
Please search in this issue tracker or on ROS Answers, this topic has been discussed at length before. This package requires properly assembled laser scan messages to operate.
