### ISSUE TITLE
Map does not grow after its initialization

### ISSUE THREAD

**Issue by mac137** [SteveMacenski/slam_toolbox#438]
**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  -  I installed this package both via `sudo apt install ros-foxy-slam-toolbox` as well as from the source (with proper sourcing of the environment). The same behavior in both cases.
- ROS Version
  -  ROS2, foxy
- Version or commit hash:
  - 48e97304618ef5b18aa38cf2ea12c41202ebc092, foxy-devel-unfixed
- Laser unit:
  - RP Lidar A1 and others downloaded from the this git repo's issues
  
#### Steps to reproduce issue

I provide the static transform between my lidar `base_scan` and odom frame 'odom' in `online_sync_launch.py`:
```
    odom_lidar_static_tf = Node(
        name='tf2_ros_odom_lidar',
        package='tf2_ros',
        executable='static_transform_publisher',
        output='screen',
        arguments=['0', '0', '0', '0.0', '0.0', '0.0', 'odom', 'base_scan'],
    )

    ...
   
    ld.add_action(odom_lidar_static_tf)

    ...
```
... and I modify `mapper_params_online_sync.yaml` like this:
```
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_scan
    scan_topic: /scan
```

and then I do `ros2 launch slam_toolbox online_sync_launch.py`

#### Expected behavior
The map should grow and build progressively as my lidar moves.

#### Actual behavior
The map stays the same after its initialization by the package like this:
![Screenshot from 2021-09-18 19-33-35](https://user-images.githubusercontent.com/60878347/133905169-fbe31e96-7313-49de-8739-9ea78e14cd40.png)

and all the time after the initialization, the map stays as above even though the lidar moved and rotated a lot:
![Screenshot from 2021-09-18 19-33-15](https://user-images.githubusercontent.com/60878347/133905401-edc52a9f-1e5a-4327-ba8d-4b180e71338f.png)

#### Additional information
After running `ros2 run tf2_tools view_frames.py` I get this TF tree:
![Screenshot from 2021-09-18 19-45-30](https://user-images.githubusercontent.com/60878347/133905432-6a9d8e43-66c8-4b9b-a41f-86843464d2fc.png)

and when I check the transform between `map` and `odom` is stays the same all the time:
```
ros2 run tf2_ros tf2_echo map odom
[INFO] [1631990416.761771843] [tf2_echo]: Waiting for transform map ->  odom: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
At time 1631990417.939988347
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
At time 1631990418.939988140
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
At time 1631990419.939991397
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
At time 1631990420.940001147
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
```

The console displays this all the time:
```
ros2 launch slam_toolbox online_sync_launch.py 
[INFO] [launch]: All log files can be found below /home/user_name/.ros/log/2021-09-18-19-52-49-142812-u20-21619
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [static_transform_publisher-1]: process started with pid [21621]
[INFO] [sync_slam_toolbox_node-2]: process started with pid [21623]
[INFO] [rviz2-3]: process started with pid [21625]
[static_transform_publisher-1] [INFO] [1631991169.189978256] [tf2_ros_fp_odom]: Spinning until killed publishing transform from 'odom' to 'base_scan'
[sync_slam_toolbox_node-2] [INFO] [1631991169.211974174] [slam_toolbox]: Node using stack size 40000000
[sync_slam_toolbox_node-2] [INFO] [1631991169.223044981] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[sync_slam_toolbox_node-2] [INFO] [1631991169.223135162] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[rviz2-3] [INFO] [1631991169.785774056] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1631991169.785861010] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-3] [INFO] [1631991169.812876302] [rviz2]: Stereo is NOT SUPPORTED
[sync_slam_toolbox_node-2] Info: clipped range threshold to be within minimum and maximum range!
[sync_slam_toolbox_node-2] Registering sensor: [Custom Described Lidar]
[rviz2-3] [INFO] [1631991173.253112738] [rviz2]: Trying to create a map of size 115 x 79 using 1 swatches
```

Any idea what I do wrong? Thanks!

**Comment by mac137** [comment]
Ofc the map does not grow because I put a static transform between `odom` and `base_frame` which is wrong. There should be an odometry method that keeps computing the relative pose between these two frames.

**Comment by amjack0** [comment]
> Ofc the map does not grow because I put a static transform between `odom` and `base_frame` which is wrong. There should be an odometry method that keeps computing the relative pose between these two frames.

Hi @maciej-3 

I am having the similar issue. Did providing the `odometry` method between two `frames` worked?
How did you solve this?  

Regards,

**Comment by mac137** [comment]
Hi @amjack0 

I wrote a simple scan-to-scan odometry node for my lidar and it works good enough for this slam package.

**Comment by maxxbolotov** [comment]
> > Ofc the map does not grow because I put a static transform between `odom` and `base_frame` which is wrong. There should be an odometry method that keeps computing the relative pose between these two frames.
> 
> Hi @maciej-3
> 
> I am having the similar issue. Did providing the `odometry` method between two `frames` worked? How did you solve this?
> 
> Regards,

Did you understand what it takes to resolve this problem?
I faced the same issue but quiet don't understand what to do.

**Comment by maxxbolotov** [comment]
> Hi @amjack0
> 
> I wrote a simple scan-to-scan odometry node for my lidar and it works good enough for this slam package.

Can you please provide step by step tutorial what I should do to resolve same issue?

**Comment by TZECHIN6** [comment]
Just hit the same issue here... the slam toolbox working just fine in the simulated robot, but when i work with the real robot... the map doesnt growth at all.

You have mentioned that the transformation is static cause this issue. First I would like to ask how do I check for myself about this?

Besides, doesnt the odom is stick with the base_frame? or you mean the base_scan should be transformed in time against the odom?

**Comment by Keegsy** [comment]
@mac137 Can you show how you wrote this node? I'm also stuck on trying to fix this issue

**Comment by Keegsy** [comment]
> Hi [@amjack0](https://github.com/amjack0)
> 
> I wrote a simple scan-to-scan odometry node for my lidar and it works good enough for this slam package.

@mac137 Can you show how you wrote this node? I'm also stuck on trying to fix this issue
