### ISSUE TITLE
[ROS2] [Turtlebot3] Wrong Visualization in RViz and Nav2 doesn't work

### ISSUE THREAD

**Issue by Niitoge** [SteveMacenski/slam_toolbox#447]
**Required Info:**

- Operating System:
  - Ubuntu 20.04.3
- Installation type:
  - binaries (apt)
- ROS Version
  - ROS2 Foxy Fitzroy
- Version or commit hash:
  - Patch Release 6.1 (commit ID 3934568d4c50aebe186d7bac101e5b4686f16ce2)
- Laser unit:
  - 360 Laser Distance Sensor LDS-01 (ROBOTIS/Turtlebot3)
  
#### Steps to reproduce issue
* Installed ROS2 according to the [setup by ROBOTIS](https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/#sbc-setup)
* Updated and upgrade everything (to get the Foxy Patch 6.1 because Foxy 6.0 had [issues](https://github.com/ros2/rviz/issues/782) with some topics in RViz)
* Install Nav2 via *apt* following the tutorial on the [Nav2 Wiki](https://navigation.ros.org/build_instructions/index.html)
* Install the slam_toolbox via *apt* following the tutorial on the [Nav2 Wiki](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html)
* Commands entered: 
```
source /opt/ros/foxy/setup.bash # in every terminal
export TURTLEBOT3_MODEL=burger
ros2 launch turtlebot3_bringup robot.launch.py 
ros2 launch nav2_bringup navigation_launch.py
ros2 launch slam_toolbox online_async_launch.py
ros2 launch nav2_bringup rviz_launch.py    # from remote PC
```

#### Expected behavior

Getting a live map feed as well as odometry and tf data in RViz2 as described in the [README](https://github.com/SteveMacenski/slam_toolbox#readme) and the [Wiki](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html).
![](https://navigation.ros.org/_images/navigation2_with_slam.gif)

#### Actual behavior

When entering:
```
ros2 launch nav2_bringup rviz_launch.py
```
I receive this all the time
![](https://i.imgur.com/yXr4lGA.png)

And the RViz looks like this:
![](https://i.imgur.com/dUeTD8r.png)

Although the map updates, the visualization is wrong and Nav2 doesn't seem to work (see RViz pic below left)

#### Additional information

When entering:
```
ros2 launch nav2_bringup navigation_launch.py
```
I receive this messages all the time:
![](https://i.imgur.com/33pljpp.png)

And when entering:
```
ros2 launch slam_toolbox online_async_launch.py
# or
ros2 launch slam_toolbox online_sync_launch.py
```
![](https://i.imgur.com/484aW2P.png)

I hope you can help me, thanks in advance :)

https://github.com/ros-planning/navigation2/issues/2651

**Comment by SteveMacenski** [comment]
Please don't cross post tickets, closing
