### ISSUE TITLE
Integrating Apriltag markers into map building and localization

### ISSUE THREAD

**Issue by ghost** [SteveMacenski/slam_toolbox#449]
#### Feature description
From sparse marker observations (AprilTag3) I would like to support (improve) the map building process in a larger environment.
Also I would like to integrate the marker observations into the localization process.

#### Implementation considerations
Both steps require the integration into the pose graph optimization module.

How would you recommend me to implement the above goals? Are there any interfaces I can use already?

**Comment by SteveMacenski** [comment]
That is out of the scope of this project.
