### ISSUE TITLE
MessageFilter [target=odom] Removed message in frame ... at time x, count now 5

### ISSUE THREAD

**Issue by francescofact** [SteveMacenski/slam_toolbox#459]
Hi,
I have a bag with 14 seconds of lidar data and tf (_carla/ego_vehicle/lidar_ and _/tf_).
I'm trying to do an offline_scan, but just one time I saw the map in rviz, all the other times it gives me "No map".
In debug mode slam_toolbox prints many times:
```
[DEBUG] [1638535964.467017944]: MessageFilter [target=odom ]: Added message in frame ego_vehicle/lidar at time 35.097, count now 5
[DEBUG] [1638535964.518764745]: MessageFilter [target=odom ]: Removed oldest message because buffer is full, count now 5 (frame_id=ego_vehicle/lidar, stamp=34.846930)
```

I use the standard launchfile with the basic configuration with just one change:
`base_frame: ego_vehicle/lidar`

Here's my bag file if you want to test it out: [lidar_tf_14_sec.bag](https://www.francescofattori.it/lidar_tf_14_sec.bag).
To play the bag I use 
`rosbag play file_name.bag --clock`
but also without _--clock_ doesn't work. It worked just a couple times, no idea way. I'm running ros noetic.
Thank you

**Comment by SteveMacenski** [comment]
These are messages relating to TF (e.g. `MessageFilter`), nothing to do with this codebase beyond the use of that tool. Please make sure you have a valid TF tree before sensor data comes through and that the clocks for simulation are set properly.

If you need further followup, please search on ROS Answers, this is a common noobie problem and there are tons of questions related to similar issues with other ROS software you can use to guide your learning.
