### ISSUE TITLE
Estimated localization trajectory of the robot as a list of TF messages using SLAM Toolbox

### ISSUE THREAD

**Issue by JehanJay** [SteveMacenski/slam_toolbox#460]
Is there a way **to obtain the estimated localization trajectory of the robot as a list of TF messages**? Ideally, at the same frequency as the laser measurements. I want to use that trajectory as the localization of my robot in TF for lookups.
Any idea on this implementation is highly appreciated. 
ROS Answers link [here.](https://answers.ros.org/question/392089/estimated-localization-trajectory-of-the-robot-as-a-list-of-tf-messages-using-slam-toolbox/)

**Comment by SteveMacenski** [comment]
Sure, if you're using TF, you can always obtain it at your desire and has almost nothing to do with AMCL / SLAM Toolbox or anything else. I'll answer in more detail in your ros answers question for searchability.
