### ISSUE TITLE
creating the map with only Lidar 

### ISSUE THREAD

**Issue by amjack0** [SteveMacenski/slam_toolbox#461]
I am using, `ROS Noetic + 20.04`
Lidar hardware:  `rplidar_a3m1`

I installed this package via `sudo apt install ros-noetic-slam-toolbox`and it is working fine.
I want to create an indoor map using `slam_toolbox` with lidar ONLY. I do not have wheel `odometry` and it's `tf`.

First I do,

- `roslaunch rplidar_ros rplidar_a3.launch` This starts publishing on the `/scan` topic.
- `roslaunch slam_toolbox online_sync.launch` I launch the `slam_toolbox` with default config.

Initially, I encounter that map did not grow after its initialization  [#438](https://github.com/SteveMacenski/slam_toolbox/issues/438) 

Then, I provided a dynamic frame as per [Broadcasting a moving frame](http://wiki.ros.org/tf2/Tutorials/Adding%20a%20frame%20%28Python%29#Broadcasting_a_moving_frame).

But I see my map is not generated correctly. It is moving in a circle (which I guess due to the `dynamic tf` I provided). The circle get smaller if I reduce the amplitude. I do not know what is the correct way of providing the `dynamic tf` between frames. 

![map](https://user-images.githubusercontent.com/52165935/145066259-409c1ef8-793f-4bca-893a-539f1bb4001f.png)

And this is how my tf tree looks like when running, `rosrun tf2_tools view_frames.py`

[frames.pdf](https://github.com/SteveMacenski/slam_toolbox/files/7669864/frames.pdf)

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers, that's a problem with whatever mechanism you're providing the TF with, which is not part of this package (or described here).
