### ISSUE TITLE
LifeLong feature testing failed

### ISSUE THREAD

**Issue by gnykumar** [SteveMacenski/slam_toolbox#470]
#### LifeLong Feature testing failed

Hi Team,

I was trying to test the LifeLong feature using an online dataset But was unable to proceed.

Steps Followed
1. Set rosparam use_sim_time true.
2. Play and keep paused Bag file
3. Run lifelong launch file
4. Play Bag file and create a small section of map
5. Save the map and serialized data (saving the file.data and file.posegraph)
6. Adding serialized data file in lifelong param file : map_file_name: "file path"
7. Rerun lifelong launch after adding serialized file and play bag file of same data.

But getting the below error

Load From File /home/yogeshkumargn/Bag_dataset/mit/Map_1/5.posegraph 
Mapper <- Module
Mapper <- m_pSequentialScanMatcher
Mapper <- m_pGraph
MapperGraph <- Graph; Graph <- m_Edges; Graph <- m_Vertices
MapperGraph <- m_pMapper; MapperGraph <- m_pLoopScanMatcher; MapperGraph <- m_pTraversal
Mapper <- m_pMapperSensorManager
MapperSensorManager <- m_ScanManagers; MapperSensorManager <- m_Scans
Mapper <- m_Listeners
**Finished serializing Mapper**
Load From File
**Serializing Dataset**
Dataset <- m_SensorNameLookup
Dataset <- m_Data
Dataset <- m_Lasers
Dataset <- m_pDatasetInfo
**Finished serializing Dataset**
Registering sensor: [Custom Described Lidar]
[ INFO] [1642995114.823869101]: Waiting for incoming scan to get metadata...
[ INFO] [1642995125.441883488, 1304083318.377693991]: Waiting for incoming scan to get metadata...
[ INFO] [1642995126.940685413, 1304083318.391504680]: Got scan!
**[ERROR] [1642995126.943418610, 1304083318.391504680]: Failed to compute laser pose, aborting continue mapping (Lookup would require extrapolation at time 1304083318.348879222, but only time 1304083318.368471701 is in the buffer, when looking up transform from frame [base_laser_link] to frame [base_link])
[slam_toolbox-1] process has died [pid 15441, exit code 255, cmd /home/yogeshkumargn/ROS_WORKSPACES/flux_mapping_ws/thor/devel/lib/slam_toolbox/async_slam_toolbox_node __name:=slam_toolbox __log:=/home/yogeshkumargn/.ros/log/57a21d9a-7cc5-11ec-846b-a0510bfa13b5/slam_toolbox-1.log].
log file: /home/yogeshkumargn/.ros/log/57a21d9a-7cc5-11ec-846b-a0510bfa13b5/slam_toolbox-1*.log**

**Comment by SteveMacenski** [comment]
The lifelong node is experimental and has no maintainer support
