### ISSUE TITLE
Unable to use exported libraries due to relative imports in header

### ISSUE THREAD

**Issue by dimasad** [SteveMacenski/slam_toolbox#471]
**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - From source
- ROS Version
  - ROS2 Galactic
- Version or commit hash:
  - fab61e1225d6c1ee5d634a4851b0a387c11c2c39
- Laser unit:
  - Any
  
#### Steps to reproduce issue
- Create a new package that depends on `slam_toolbox`. 
- Include `slam_toolbox/slam_toolbox_common.hpp` or `slam_toolbox/serialization.hpp` to deserialize a posegraph, for example.
- Attempt to compile.

#### Expected behavior
The toolbox types can be used in another package.

#### Actual behavior
It fails to compile because the imports in the headers are relative, so only `slam_toolbox` can be compiled. There's a comment that says "god... getting this to work in ROS2 was a real pain", so I believe that it the fix broke inter-package compatibility.

**Comment by SteveMacenski** [comment]
PRs have been merged - closing
