### ISSUE TITLE
catkin_make failed.

### ISSUE THREAD

**Issue by Lee-JaeWon** [SteveMacenski/slam_toolbox#482]
**Required Info:**

- Operating System:
  - Ubuntu 20.04 LTS
- Installation type:
  - catkin make
- ROS Version
  - ROS1 Noetic
- Version or commit hash:
  - 
- Laser unit:
  - 
  
#### Steps to reproduce issue
After downloading the noetic-develop branch, catkin_make was performed. I checked Cmakelists and installed the necessary package, but the following error phrase appears.

```
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "sparse_bundle_adjustment" with any of the following names:

    sparse_bundle_adjustmentConfig.cmake
    sparse_bundle_adjustment-config.cmake

  Add the installation prefix of "sparse_bundle_adjustment" to
  CMAKE_PREFIX_PATH or set "sparse_bundle_adjustment_DIR" to a directory
  containing one of the above files.  If "sparse_bundle_adjustment" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  slam_toolbox/slam_toolbox/CMakeLists.txt:14 (find_package)


```
What more requirements should I install?

Thank you in advance.

**Comment by tugbakara** [comment]
how did you solve it? I have the same error
