### ISSUE TITLE
Custom Described Lidar

### ISSUE THREAD

**Issue by 885288421** [SteveMacenski/slam_toolbox#486]
ubuntu:20.04
ros2:foxy
Lidar：EAI G4
I want to creat a map by slam_toolbox,but it tell me :[sync_slam_toolbox_node-1] Registering sensor: [Custom Described Lidar]
in rviz2 it same have work a short time,the map don't have update,I run ros2 topic echo /map_updates, but it don't have any responses，I only want to creat a map，can you help me？

**Comment by SteveMacenski** [comment]
Ask on ROS Answers please, or look at previous answers / software requirements.
