### ISSUE TITLE
Message type sensor_msgs/msg/LaserScan is not detected by slam toolbox

### ISSUE THREAD

**Issue by maksimmasalski** [SteveMacenski/slam_toolbox#492]
**Required Info:**
I have sick lidar and software for running it https://github.com/SICKAG/sick_safetyscanners2 
In API it says Advertised ROS2 Topics `~/scan (type: sensor_msgs/msg/LaserScan)`
But API in slam toolbox says `sensor_msgs/LaserScan`

Can it be an issue that I described in issue #491 Message Filter dropping message: frame 'scan' for reason 'Unknown' ?

Is it a significant difference for slam toolbox  `sensor_msgs/msg/LaserScan` and `sensor_msgs/LaserScan`

**Comment by SteveMacenski** [comment]
As I said in your last ticket, you need to have real odometry to get through the filter so that there's a valid transformation from odom->laser_link. Just a laser scan is insufficient.
