### ISSUE TITLE
How to download the sample data?

### ISSUE THREAD

**Issue by DreamWaterFound** [SteveMacenski/slam_toolbox#493]
Excellent work!

I want to test the entire system using the sample data which mentioned in [README.md](https://github.com/SteveMacenski/slam_toolbox/blob/noetic-devel/README.md):

> The video below was collected at [Circuit Launch](https://www.circuitlaunch.com/) in Oakland, California. Thanks to [Silicon Valley Robotics](https://svrobo.org/) & Circuit Launch for being a testbed for some of this work. This data is currently available upon request, but its going to be included in a larger open-source dataset down the line.

Could you please tell me where I can download this dataset? 

Thanks!

**Comment by SteveMacenski** [comment]
Removing from readme, that was a project that didn't get legs so its not available.
