### ISSUE TITLE
No blue links between red dots of the graphs

### ISSUE THREAD

**Issue by maksimmasalski** [SteveMacenski/slam_toolbox#498]
**Required Info:**

- Operating System:
  - Ubuntu 20.04.4 LTS
- Installation type:
  - from source
- ROS Version
  - ROS2 foxy
- Version or commit hash:
  - 99e12e5c0df4428a45d05195e3a121272208c808
  
#### Steps to reproduce issue
I don't see blue links between red dots of the pose graph in ROS2 foxy. At the same time in ROS1 I can see blue link connections between them. Image here shows my ROS2 behavior:
<img width="660" alt="ros2_no_links" src="https://user-images.githubusercontent.com/54880286/172876612-ef0ebb2f-bc9e-4ccb-9c30-5b168e0fb900.png">

For example in ROS1 map looks like this:
<img width="636" alt="ros1_links_appear" src="https://user-images.githubusercontent.com/54880286/172893272-41438895-391c-41ad-a66d-c498cca8b094.png">

**Comment by SteveMacenski** [comment]
https://github.com/SteveMacenski/slam_toolbox/pull/467 That feature was added to ROS 1 as a user contribution. If you'd like to forward port to ROS 2, I'd accept a PR but its not a critical feature.

**Comment by maksimmasalski** [comment]
> #467 That feature was added to ROS 1 as a user contribution. If you'd like to forward port to ROS 2, I'd accept a PR but its not a critical feature.

Thank you, Steve, for the fast reply, and your support. Because without it, I would spend days figuring out where is the difference.
