### ISSUE TITLE
Get the robot trajectory path plot in Rviz2 by Slam toolbox

### ISSUE THREAD

**Issue by JehanJay** [SteveMacenski/slam_toolbox#501]
Hello, 

Even though the map is generated by the Slam toolbox, the trajectory path (preferably with a line) is not shown in Rviz2 with the Slam toolbox. However, instead of a line, the trajectory is shown with multiple dots which is not what I needed.

Is there a way to fix this issue and get the trajectory path in RViz2 with a line in the generating Map itself?

Also, this question is asked in [RosAnswers](https://answers.ros.org/question/402372/how-to-get-the-robot-trajectory-plot-in-rviz2-by-slam-toolbox/) here.

Thanks

**Comment by SteveMacenski** [comment]
Please do not cross post from ROS Answers, I'll follow up there. That question was only posted 7 hours ago, or 3 AM my time, obviously I can't respond instantly.
