### ISSUE TITLE
Odometry relies too heavily on visual odometry

### ISSUE THREAD

**Issue by Ido220694** [SteveMacenski/slam_toolbox#525]
My odometry relies too heavily on visual odometry, so when there are no visual elements there is rapid distraction.
How does slam_toolbox know to handle a situation where the odometry diverges quickly in a certain direction? Is there a way to let the tool_box mechanism detect such a situation and cover it with scan matching? 
Thanks

**Comment by SteveMacenski** [comment]
This is a good question for ROS Answers, but generally this is a graph slam question.
