### ISSUE TITLE
[sync_slam_toolbox_node-3] [INFO] [1666050381.371960267] [slam_toolbox]: Message Filter dropping message: frame 'rplidar_link' at time 1666050381.236 for reason 'discarding message because the queue is full'

### ISSUE THREAD

**Issue by MoYasser** [SteveMacenski/slam_toolbox#543]
**Required Info:**

- Operating System:
  Ubuntu 20.04 & 22.04
- Installation type:
  Binary
- ROS Version
  ROS 2 Galactic & Humble
- Version or commit hash:
 Latest
- Laser unit:
  RPLidar A1M8
#### Additional information
I keep getting this Error everytime i try to run slam_toolbox with my rplidar and i dont know what else to fix in my code <Tried importing some turtlebot4 code into mine but still no difference at all>

not sure if it is memory thing or am i missing something im pretty new with it and learning it.

Would appreciate the help on what to do or how to fix my code :) thanks in advance

Github Repo:
https://github.com/MoYasser/slambot_core

**Comment by SteveMacenski** [comment]
Please search on or ask on ROS Answers
