### ISSUE TITLE
No map received?

### ISSUE THREAD

**Issue by Marouan-22** [SteveMacenski/slam_toolbox#555]
hi everyone,

I am using the foxy-devel repo to work on my lidar (RPLidar A1) project and hopfully maps the environment if the problem is solved, but it doesn't?

![image](https://user-images.githubusercontent.com/61140897/203420987-79a0865e-b92a-4e20-8511-b42dd3c3b3f1.png)

Does anyone has an idea how to solve it! it will be very much appreciated!

Greetings !

**Comment by SteveMacenski** [comment]
Is data getting to slam toolbox with the relevant transforms?

please ask / search on ROS Answers
