### ISSUE TITLE
No tf data.  Actual error: Frame [base_footprint] does not exist

### ISSUE THREAD

**Issue by OforiDarren** [SteveMacenski/slam_toolbox#556]
Hello all! Issue is in the title and in this picture. I use Ubuntu 22.04 and Humble.
![afbeelding](https://user-images.githubusercontent.com/69010858/203380821-ce9f9a53-f332-4fb0-836a-48bb2c5c703b.png)
I executed these commando's: 
![afbeelding](https://user-images.githubusercontent.com/69010858/203381374-f7f192af-ba12-4870-b13f-847a6a4f09f1.png)
![afbeelding](https://user-images.githubusercontent.com/69010858/203381472-adab1824-7497-439c-a157-017d5e6e52b0.png)

Can anyone please help me with my issue?

**Comment by SteveMacenski** [comment]
Please ask on ros answers
