### ISSUE TITLE
Profiling and Accelerating SLAM_Toolbox for Implementation on an FPGA

### ISSUE THREAD

**Issue by mpurushothapu3** [SteveMacenski/slam_toolbox#557]
Hello,
I am part of a group researching ROS2 algorithms to look for opportunities for acceleration, especially on an FPGA. We are currently of profiling SLAM_Toolbox as part of our research and we are currently using Callgrind as a profiling tool to identify potential bottlenecks and KCacheGrind as a visualization tool; however, Callgrind, while identifying functions with high cost, does not give us a detailed function call diagram or a code map. We were wondering if you had any suggestions to better understand the code in SLAM_Toolbox, such as understanding data dependencies, generating a time graph, or generating a code map in order to help us understand the code better to find opportunities for acceleration.
Thank you so much for your time.

**Comment by SteveMacenski** [comment]
I don’t have any additional resources for you
