### ISSUE TITLE
No pose topic published from slam_toobox

### ISSUE THREAD

**Issue by GregoireScf** [SteveMacenski/slam_toolbox#559]
**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 Foxy
- Laser unit:
  - Sick MicroScan3
  
#### Steps to reproduce issue
I'm trying to use slam_toolbox in localization mode to get the pose topic published from the package as it is specified in the documentation.
Basically, after successfully mapped and save my environment, I tried to run all 3 differents launch files in localization mode and everything work super good but the position is not published from slam_toolbox

#### Expected behavior
/pose should be published as geometry_msgs/PoseWithCovarianceStamped message 

#### Actual behavior
no pose topic is published

#### Additional information
I noted that some of my lidar frame are dropped when I launch the nodes but my guess was that my laser scan rate was too high and  that it should not be a problem make things work, right ?

**Comment by SteveMacenski** [comment]
Please ask on Ros answers

**Comment by PallottaEnrico** [comment]
Did you find a solution?

**Comment by GregoireScf** [comment]
I've explain my workaround [here](https://answers.ros.org/question/409825/slam_toolbox-no-pose-topic-published/)
