### ISSUE TITLE
add support for PointCloud2 msgs

### ISSUE THREAD

**Issue by rsc9421** [SteveMacenski/slam_toolbox#565]
#### Feature description
It could be very useful if slam_toolbox would accept PointCloud2 messages, since passing them to LaserScan manually is usually a paintful

#### Implementation considerations
I have tried trying to convert the message manually and I had no successful results, I have also tried this package https://github.com/ros-perception/pointcloud_to_laserscan and I did not have satisfactory results either

**Comment by SteveMacenski** [comment]
Not in the roadmap
