### ISSUE TITLE
Details on Scan Matching Algorithm used in SLAM_Toolbox

### ISSUE THREAD

**Issue by mpurushothapu3** [SteveMacenski/slam_toolbox#570]
The documentation of slam_toolbox state that the scan matching algorithm of Karto SLAM in the old open_karto repository has very good performance and is well-known; however, it's difficult to find papers on the method implemented or figure out what method was implemented. Is there any more detail or documentation on the scan matching algorithm used, such as the type (ICP or CSM, etc.)?

**Comment by SteveMacenski** [comment]
Ask on ROS Answer or read the Karto papers.
