### ISSUE TITLE
Pose publisher for ROS1

### ISSUE THREAD

**Issue by graiola** [SteveMacenski/slam_toolbox#577]
#### Feature description

Hi, I noticed that the pose publisher for ROS1 is missing. Is it going to be added in the future? Thank you.

**Comment by SteveMacenski** [comment]
Its not the plan unless it is contributed by the community. I typically don't think about ROS 1 greatly anymore

**Comment by graiola** [comment]
I made a PR for ros melodic, but it should run on noetic as well.

**Comment by SteveMacenski** [comment]
Great! I took a look though, it looks like you pulled in a bunch of other changes that should be removed so we can review it for just the changes to enable the feature. Right now, its so ungodly large I cannot possibly review it

**Comment by graiola** [comment]
I copied the `lib/karto_sdk` folder from the ros2 branch. I figured that it is an updated and ros2 independent version of `karto_sdk`. Is that correct? Otherwise, how can I proceed to make the review easier? 

Meanwhile I am running tests with `slam_toolbox` and my ros1 navigation stack (Ubuntu 18.04 and Ubuntu 20.04)  and it seems to work correctly.

**Comment by SteveMacenski** [comment]
I looked at your new changes, they look good except minor things!
