### ISSUE TITLE
A2 lidar always sends 0,0,0 data as distance information, the lidar light(red) is not seen

### ISSUE THREAD

**Issue by Dev-Mani-Hdr** [SteveMacenski/slam_toolbox#579]
**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- ROS Version
  - 
- Version or commit hash:
  - 
- Laser unit:
  -

**Comment by Dev-Mani-Hdr** [comment]
A2 lidar always sends 0,0,0 data as distance information, the lidar light(red) is not seen.

Initial it worked well for some time around 30hrs, later all the distance information has become 0,0,0  and the lidar light(red) is not glowing.

What could be the issue?

Can we get any service support, we are from Bengalure India.

**Comment by SteveMacenski** [comment]
I’m not your lidar’s manufacturer, contact them about hardware failures
