### ISSUE TITLE
No Map received using SLAM

### ISSUE THREAD

**Issue by Kathan-k10** [SteveMacenski/slam_toolbox#591]
Please provide the following information:

OS: ubuntu Ubuntu 22.04.2 LTS
ROS Distro: Humble
Built from source or installed: Built from source

I am using RPLidar a1 and I am trying to do SLAM with that. Currently I have not connected the robot only playing with Lidar. I am following all the steps to Implement SLAM but I not not getting anything on the Rviz. and on the console with SLAM command I getting the error: Message Filter dropping message: frame 'laser' at time 1679982623.312 for reason 'discarding message because the queue is full'

To Reproduce
Provide the steps to reproduce: First only use Lidar connected with laptop with ros2 and turtlebot4 installed

1)run: ros2 launch ros2 launch rplidar_ros rplidar.launch.py
on one terminal
2)run:ros2 launch slam_toolbox online_async_launch.py
Other notes
![Screenshot from 2023-03-29 15-45-11](https://user-images.githubusercontent.com/88841915/228510114-adffac74-854a-4b03-93b5-6ab21f187fd6.png)

**Comment by SteveMacenski** [comment]
Ask on ROS Answers
