### ISSUE TITLE
Pose topic 

### ISSUE THREAD

**Issue by rsc9421** [SteveMacenski/slam_toolbox#593]
- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 foxy

 
The readme says that there is a /pose topic (type:  geometry_msgs/PoseWithCovarianceStamped) that publish the transform map_frame to base_frame, but it doesn't appear in the topics list when I run mapping or localization mode (the mapping works fine)

**Comment by SteveMacenski** [comment]
Frankly, Foxy is so out of date w.r.t. Nav2 and related projects that we don't really backport or perform updates to it anymore. The entire distribution is EOL is about 3.5 weeks so I don't think its worth the maintainer's time to try to backport that and other fixes to foxy. That distributions is nearly sunsetted and very far behind the state of the art. 

I know this is probably not what you want to hear, but I just want to be honest with you to give you the reality of it from my perspective.
