### ISSUE TITLE
Not able to save map

### ISSUE THREAD

**Issue by etigafy** [SteveMacenski/slam_toolbox#604]
**Required Info:**

- Operating System: Ubuntu 22.04
- Installation type: installed
- ROS Version: ROS2 Humble
- Laser unit:
  - RP Lidar A1
  
#### Steps to reproduce issue
1. ros2 launch turtlebot4_navigation slam.launch.py namespace:=/robot2
2. ros2 launch turtlebot4_viz view_robot.launch.py namespace:=/robot2
3. ros2 service call /robot2/slam_toolbox/save_map slam_toolbox/srv/SaveMap "name:
  data: 'my_map'"

#### Expected behavior
SaveMap service saves the map in the current location
#### Actual behavior
```
ros2 service call /robot2/slam_toolbox/save_map slam_toolbox/srv/SaveMap "name:
  data: 'my_map'"
requester: making request: slam_toolbox.srv.SaveMap_Request(name=std_msgs.msg.String(data='my_map'))

response:
slam_toolbox.srv.SaveMap_Response(result=255)
```
Service responds with undefined failure. I tried it with a namespaced robot.

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers

**Comment by SteveMacenski** [comment]
See comments in https://github.com/SteveMacenski/slam_toolbox/issues/607
