### ISSUE TITLE
Mapping when only spin

### ISSUE THREAD

**Issue by zvweaf** [SteveMacenski/slam_toolbox#606]
First of all thanks a lot for your open source work. I have a problem now, when I can only spin, how to set the parameters so that the map can be constructed every 45 degrees？

**Comment by SteveMacenski** [comment]
Hi,

This PR basically implements it but needs a little work before I can merge it in + release to all the distributions: https://github.com/SteveMacenski/slam_toolbox/pull/451

If you'd like to take the torch, I'd be happy to review PRs and have it merged and re-released by this time next week for you to use

**Comment by zvweaf** [comment]
Thank you very much for your reply, I will try it out
