### ISSUE TITLE
Initial map params

### ISSUE THREAD

**Issue by malaksayour** [SteveMacenski/slam_toolbox#608]
#### Feature description

I'm trying to build 2 maps using 2 different agents and I want to merge both together. For that I would like my robot start pose (whenever the mapping starts) to be in the center of the map and preferable to have a size matching the map I'm receiving from agent2. Is there a way to initialise the mapping with a fixed size and with the robot being at the center of the map?

**Comment by SteveMacenski** [comment]
Not easily, no. But you can see your odometry with a pose that should get that for you approximately.
