### ISSUE TITLE
Slam_toolbox with robot localization package

### ISSUE THREAD

**Issue by hmpcjayaweera** [SteveMacenski/slam_toolbox#611]
Hi,
I need to use the filtered_odom of the robot localization package instead of odometey frame in Slam toolbox. Because the output localize odometery  is more accurate than the /odom. Please can you explain how to do that. thanks

**Comment by SteveMacenski** [comment]
You're in luck, we literally don't use the `/odom` topic and only use the odometry from robot localization or whatever is providing the `odom->base_link` transform (usually robot localization). So if you're using RL to provide you your odometry and have publication to TF setup, you're already done!
