### ISSUE TITLE
map origin queries

### ISSUE THREAD

**Issue by futuristic2023** [SteveMacenski/slam_toolbox#616]
image: slam_wh_map_wr_1cm.pgm
mode: trinary
resolution: 0.01
origin: [-30.1, -24.9, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25

height and width of the map are 3968 and 4900 pixels

how the origin value is calculated

**Comment by SteveMacenski** [comment]
Its based in part on the starting pose wrt the map as its created and the initial odometry pose at the stating point. But the origin is completely arbitrary as long as its consistent, it doesn't matter its value (either on the map, in the center, off the map, 1km away from the map, etc)
