### ISSUE TITLE
Can not Continue Mapping 

### ISSUE THREAD

**Issue by AdrianCobo** [SteveMacenski/slam_toolbox#618]
Required Info:

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - source
- ROS Version
  - ROS2
- Version or commit hash:
  - 
- Laser unit:
  - gazebo
  
#### Steps to reproduce issue
modify my mapper_params config file .yaml: 
slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: localization # mapping # localization

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    map_file_name: /home/Desktop/ros2_course/a
    # map_start_pose: [-3.8019, -3.101, 0.0]
    map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

and launch:
$ ros2 launch slam_toolbox online_async_launch.py params_file:=./src/my_bot/config/mapper_params_online_async.yaml

* a is the name of the .posegraph and .data files of my previous mapping

#### Expected behavior
sow in rviz the previous mapping and continue mapping

#### Actual behavior
previous mapping is not loaded
#### Additional information
debug info from after launch:
[INFO] [launch]: All log files can be found below /home/adrianco/.ros/log/2023-06-27-01-00-24-785773-adrianco-GL65-9SEK-6505
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [async_slam_toolbox_node-1]: process started with pid [6506]
[async_slam_toolbox_node-1] [INFO] [1687820424.932904096] [slam_toolbox]: Node using stack size 40000000
[async_slam_toolbox_node-1] [INFO] [1687820425.383240763] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-1] [INFO] [1687820425.383550578] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[async_slam_toolbox_node-1] [INFO] [1687820425.467648777] [slam_toolbox]: Message Filter dropping message: frame 'laser_frame' at time 477.477 for reason 'discarding message because the queue is full'
[async_slam_toolbox_node-1] [WARN] [1687820425.475592917] [slam_toolbox]: maximum laser range setting (20.0 m) exceeds the capabilities of the used Lidar (12.0 m)
[async_slam_toolbox_node-1] Registering sensor: [Custom Described Lidar]
[async_slam_toolbox_node-1] [INFO] [1687820425.762670391] [slam_toolbox]: Message Filter dropping message: frame 'laser_frame' at time 477.777 for reason 'discarding message because the queue is full'
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[async_slam_toolbox_node-1] [INFO] [1687820553.971945989] [rclcpp]: signal_handler(signum=2)
[INFO] [async_slam_toolbox_node-1]: process has finished cleanly [pid 6506

**Comment by SteveMacenski** [comment]
Ask on ros answers
