### ISSUE TITLE
Drift when using multi-scan merged 360 FOV

### ISSUE THREAD

**Issue by LotfiZ** [SteveMacenski/slam_toolbox#628]
**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - From Source
- ROS Version
  - ROS Melodic
- Version or commit hash:
  - commit 7987d70
- Laser unit:
  - 2x Sick NanoScan 270 degrees FOV
  
#### Steps to reproduce issue
I'm using the toolbox to map a large factory, as the NanoScan limited FOV, i used a merger to have one source of scan that cover 360. I used both modes : async ( with real time data) and offline (with bag file), i had same results with both. However, i tried three different setups : 1- Mapping with full FOV (merged scan), 2- Mapping with only front laser (270 FOV), 3- Mapping with full FOV + disable scan matcher in the config.

The main issue is that with first setup -Mapping with full FOV (merged scan)- there is a drift at the end of the mapping (see picture in actual behavior), but when trying with second and third setup, no drift noticed (see picture in expected behavior)

#### Expected behavior

![dataset • ipl_defaut_sans_sm_original_scan](https://github.com/SteveMacenski/slam_toolbox/assets/41443752/c2922b49-cada-4334-be2f-fba7fa8fcb27)

#### Actual behavior

![ipl_default_penalty_sm](https://github.com/SteveMacenski/slam_toolbox/assets/41443752/4ba3f638-bb8d-4f49-ba55-fcb71c67582c)

#### Additional information

For the first setup, i tried the default parameters, then modifying the scan matcher parameters, same result each time. Plus, while mapping with the full FOV, i was following the robot (dynamic obstacle)

**Comment by SteveMacenski** [comment]
Is it possible that there's an issue with your scan merging technology and/or its output population of the laser scan message? 

Basically how I read this ticket is that everything works great with laser scans coming from the hardware (which this was designed for), but the issue appears when you merge them. I'd look at the merging / output laser scans to make sure there isn't some small error being introduced.

**Comment by LotfiZ** [comment]
Hi Steve, thanks for the quick feedback ! 

Basically for the merging, i'm using the well known package `ira_laser_merger` and i'm already using the merged scan to compute odometry with scan matching algo and its quite good. Now maybe the redundant measurement present in merged scan can cause some errors in the scan matching in slam_toolbox. In addition, the merged scan interpret the INF or NaN values as range_max + 1.

I'm attaching a bag file from where i recorded the individual scans, the merged scan and TFs :  

[https://drive.google.com/file/d/1vsTCo5V7Tb5nzAZsFCNh-0ZWT6EMJS8h/view?usp=sharing](url)

N.B : Maybe its better to map with a limited FOV (270 for example) instead of full coverage in my case...i had this thinking after watching this : [https://www.youtube.com/watch?v=YrlEQ1sTLVw&ab_channel=SRIkarto](url)

Thank you !

**Comment by SteveMacenski** [comment]
> Now maybe the redundant measurement present in merged scan 

I'm not sure what redundant measurement you mean, but yes, any kind of incorrect population of the laser scan message will mess with this. This package assumes a constant, evenly spaced number of samples as would be produced by any professional lidar platform. If the laser scan merger doesn't do this, then you may have some problems. 

This extra drift though _may_ also be resolved once you actually have a loop closure in that last upper area for it all to snap back together. Its not great that the extra drift is happening in the first place, but I suspect its to do with the format of data coming back in (or has to do with the merged scan odometry you're using rather than SLAM itself -- does this issue occur when you use a single laser for odometry + 2 scans for SLAM?)

**Comment by LotfiZ** [comment]
> I'm not sure what redundant measurement you mean

Yes sorry its unclear, i mean there is some measurement overlapping when merging two lasers (just in a small portion in the measurements).

> does this issue occur when you use a single laser for odometry + 2 scans for SLAM?)

Never test this setup but i know that if i only use a single laser with limited FOV (270 in our case) to compute odometry from scan matcher, it eventually drifts, but i'll give a try to this configuration. However in same context i can say that using the merged scan in the computation of the odometry using scan matching ( i.e CSM ), the result are correct. 

To give additional information, i test the following : merged scan for odometry + merged scan for SLAM with scan_matcher parameters = False. i had no drift in this case.  

![image](https://github.com/SteveMacenski/slam_toolbox/assets/41443752/5fc5af05-9f12-444f-bc5c-6b15cd9a82a7)
Example of the merged lasers

**Comment by SteveMacenski** [comment]
I'd have to understand how that data is structured, but it looks like a strong potential to me that they're either not properly ordered or not evenly distributed in either sampling time or sampling angular resolution -- which is a core consistency of laser scanners which we use here. This might not matter to a tool that converts this into a PC2 for use in scan-to-scan matching, but it matters when we treat it as a structured set of data in a laser scanner format which contains information like scan time and scan resolution (e.g. the angular band per measurement) **which needs to be consistent and accurate** for this to work properly. Given that there appears to be (which could be wrong; photo resolution isn't that high) multiple points overlapping each other in the same spatial point, that precludes whatever scan assembler you're using from being a well formatted laser scan with the regularity required and assumed with a **properly** populated laser scan message, which is required for sensitive applications like this. 

If that's the case, the solution is simple but perhaps will take some time: use a better scan assembler which creates a proper laser scan message with proper spacing and timing as expected from the output of any given laser scan message. 

This wouldn't matter for anything that converts it into spatial coordinates (PC2, Voxel layer, etc). Many applications of laser scans actually do this. But we use the actual laser scan data and the metadata provided to us for scan matching which adds a great degree of accuracy + reduces the compute time for sensor matching (+ reduces the amount of data stored in RAM)

**Comment by SteveMacenski** [comment]
https://github.com/iralabdisco/ira_laser_tools/blob/ros1-master/src/laserscan_multi_merger.cpp#L207 Looking over this - its _very_ approximate. That is likely the source of error. You could prove that to yourself if you virtually converted one of your 270 deg lidars into a 360 deg lidar by populating 90 degrees of 0's or INF's to show it works fine otherwise (and its not related to the 360-ness, but the data contained in it from the merger)

Approximate computations will easily add error into a system - so its not surprising to me to see performance degrade. I'm surprised how well it does otherwise given the assumptions in the scan matcher's data.

**Comment by LotfiZ** [comment]
Thank you very much Steve for this clarification, i'll definitely look into the merging as its a critical point for AMRs -generally this kind of industrial robot has two security lasers-. 

i'll close this ticket if you agree.

Thanks !
