### ISSUE TITLE
Odometry Subscription

### ISSUE THREAD

**Issue by brukg** [SteveMacenski/slam_toolbox#629]
#### Feature description
slam tools like cartographer allow odometry fusion
is the same true for slam_toolbox since I couldn't find a way to use an odometry source along with Lidar scans? if it is not the case is there a particular reason that it only uses scans? I am asking this because while mapping a large area using only Lidar the map is not as good as using cartographer(scan and odom) may be i need to tweak some parameters?

**Comment by SteveMacenski** [comment]
Odometry is used through the TF2 interface from the odom->base link transform, which should be the output of whatever odoemtry fusion technique that you utilize (e.g. Fuse, Robot Localization, custom). We don't take it over the topic but the TF2 transform. The readme is pretty clear about that I think: https://github.com/SteveMacenski/slam_toolbox#subscribed-topics

**Comment by brukg** [comment]
Yes you are right about the tf. Just to clarify what I meant is does the scan matcher make use of this tf data to improve the scan matching?
