### ISSUE TITLE
Robot Jumps in Multiple Narrow Corridor

### ISSUE THREAD

**Issue by esamet** [SteveMacenski/slam_toolbox#631]
Hi ı have a map like that, my problem is when drive between corridors robot suddenly jump the near corridor, does anyone have this issue?
I use 22.04 Humble
![image](https://github.com/SteveMacenski/slam_toolbox/assets/60717099/1bd06ef0-760b-4524-bcda-97d35e593a34)

![image](https://github.com/SteveMacenski/slam_toolbox/assets/60717099/92f19390-2034-4b53-8e4a-0537162684d2)

**Comment by SteveMacenski** [comment]
This is possibly better for Robotics Stack Exchange and provide more description as to what you find in particular wrong.
