### ISSUE TITLE
Add publish_tf parameter

### ISSUE THREAD

**Issue by mariamercade** [SteveMacenski/slam_toolbox#638]
#### Feature description
I propose adding a new feature to the slam_toolbox that would enhance its usability in scenarios where multiple robot_localization nodes are used. Currently, I have two localization nodes running: a `local_ekf` node (which publishes the tf from `odom` to `base_link`) and a `global_ekf` node (which establishes the transformation between `map` and `odom`). This is the setup:

![issue](https://github.com/SteveMacenski/slam_toolbox/assets/99649963/09f0b97b-f1f8-423f-9dbb-1c42f8e6dbbc)

Depending on whether I am in navigation or mapping mode, the `global_ekf` takes either the `amcl_pose` or the `slam_pose` as input. However, I've encountered an issue when performing mapping tasks. Both the `global_ekf` and `slam_toolbox` independently publish the transform between `map` and `odom`. To overcome this, I suggest introducing a new boolean parameter, `publish_tf`, which, when set to true, will enable the slam_toolbox to publish the `map` to `odom` transform, and when set to false, it will disable this publication. 

This feature enhancement would greatly benefit users like me who require the precision of the `global_ekf` for mapping tasks.

#### Implementation considerations
To implement this feature, we need to make changes to the slam_toolbox codebase to introduce the `publish_tf` parameter and stop sending the map to odom transform when it is set to false.

Please let me know if there's any additional information needed or if you have any questions about this proposal.

Thank you!

**Comment by SteveMacenski** [comment]
Set transform_publish_period to 0.0 and it’ll stop publishing TF
