### ISSUE TITLE
Need help to publish odometry

### ISSUE THREAD

**Issue by jesusramondovale** [SteveMacenski/slam_toolbox#639]
Hi! 

I'm using a custom robot with two linear fixed motors, and a IMU (a basic differential drive)
I'm executing Ubuntu 22.04 with ROS2 Humble on a DEBIX Model-A SBC, and a Portenta board who communicates the commands to the motors. 
I succesfully created the robot's URDF file with all joints and links: 

![Captura desde 2023-10-03 15-27-13](https://github.com/SteveMacenski/slam_toolbox/assets/71335809/90fc585f-7a0d-4962-8e55-71fb03c74f78)
![Captura desde 2023-10-06 14-06-20](https://github.com/SteveMacenski/slam_toolbox/assets/71335809/519e6a72-4bb8-42f6-9fd3-8c34f8e9f4ee)

And also I've achieved to start mapping: 
![Captura desde 2023-10-06 14-04-00](https://github.com/SteveMacenski/slam_toolbox/assets/71335809/3a791689-522f-4c64-8c69-cd7fe9e2baf0)

The problem is, when we move the robot it doesn't know it because nobodys publishing the odometry on /odom topic, nor the odom->base_link transform on /tf 

As I said, we've got a Intel Realsense camera who publishes the IMU values at /camera/camera/imu, and a "/portentatopic" where the current speeds of each motor are published. 

I wonder if anyone could help us with creating a node to publish o /odom and /tf. 

Thank you so much!

**Comment by SteveMacenski** [comment]
Checkout first time robot setup guide on navigation.ros.org

**Comment by jesusramondovale** [comment]
I've already checked the set up guide but I don't know what I must do with the IMU and current speeds values in order to get the odometry values published. 

I could also use the diff_drive_controller package but I don't know how to either

**Comment by SteveMacenski** [comment]
https://navigation.ros.org/setup_guides/odom/setup_odom.html#robot-localization-demo goes into detail with links to appropriate resources.

**Comment by jesusramondovale** [comment]
I'm using ROS2 and the demo example given is using ROS1 libraries.. 

Nevermind.. I succesfully made a ROS2 odometry publisher using my two linear velocities.. but I have no idea how to publish the odom -> base-link transform
