### ISSUE TITLE
Is there anyway to clean current map and rebuild a new map?

### ISSUE THREAD

**Issue by HuskyKingdom** [SteveMacenski/slam_toolbox#640]
#### Feature description

Is there any way to clean the current map and rebuild a new map? I am now using the slam toolbox as a map builder for my RL task, when I reset the episode the environment might change, therefore I was wondering is it possible to rebuild a new map without rebooting the node. I didn't find any similar servers provide this functionality.

**Comment by SteveMacenski** [comment]
Not at this time. However that seems like a reasonable enough service to have added if you wanted to contribute it!

**Comment by j3soon** [comment]
Hi @SteveMacenski, I would like to try implement this feature. Could you provide some guidance on the preferred approach to implement it?

My preliminary idea is to create a clear map service `/slam_toolbox/clear_map`. This service will aquire the `smapper_mutex_` lock and then call `Mapper::Reset`. Subsequently, in the following call to the `Mapper::Process*` functions, `Mapper::Initialize` would be indirectly invoked.

Does this approach sound reasonable, or have I overlooked anything?

**Comment by SteveMacenski** [comment]
I'd look at all the member objects and make sure you address each of their states when the map is reset. It will indeed require the mutex when modifying the mapper object to kill the current session and make a new one

**Comment by i1Cps** [comment]
Not sure on the progress of this feature, but I'm interested on working on it with you

**Comment by SteveMacenski** [comment]
#673 addresses
