### ISSUE TITLE
SLAM not working on SBC Debix Model-A

### ISSUE THREAD

**Issue by jesusramondovale** [SteveMacenski/slam_toolbox#641]
Hi, I'm using the slam_toolbox package on an SBC DEBIX Model A (2GB RAM) and this specs:

- Microprocessor:
  - i.MX 8M (ARM64)
- Operating System:
  - Ubuntu 22.04 
- Installation type:
  - Binaries (apt-get install)
- ROS Version
  - ROS2 Humble Hawksbill 
- Laser unit:
  - SICK NanoScan3

I succesfully made a map of my room executing all nodes on my DEBIX -except the slam node, which was executed on my Ubuntu Virtual Machine on my x86-64 laptop- but when I try to execute ALL nodes (slam node included) on my DEBIX board, it won't make a map, only just the first "photo". It doesn't continue making the map as it does when slam is executed on my laptop VM

![image](https://github.com/SteveMacenski/slam_toolbox/assets/71335809/8aa3eb4b-44df-46b8-a5eb-ad75d5e0aab9)

Do you know whay may be causing this?

**Comment by SteveMacenski** [comment]
Nope. Perhaps check htop if your computer is thrashing in the CPU or ran out of memory. I think by your experiment you show that SLAM Toolbox works fine, but its its a hardware related issue, so I’d look there. 

I know I’ve done this on Jetsons and other ARM systems, but I don’t know much about your particular board

**Comment by jesusramondovale** [comment]
Hi! I've checked it's not a RAM problem (executing all nodes on the SBC only use 1.25GB RAM), but all its 4 cores are +90%. 
May it be something related to CPU usage? 

![image](https://github.com/SteveMacenski/slam_toolbox/assets/71335809/60b0b59a-f50c-451f-87bd-20ec78241ca2)

I repeat: executing the same node on a external VM on a LAN network maps all fine, but not in te SBC

Do you know if I could use another type of mapping (offline / async) ?

**Comment by jesusramondovale** [comment]
Tried all modes and no one worked :(

**Comment by SteveMacenski** [comment]
I think that htop image speaks for itself. You're out of compute power, you don't have any left to run SLAM unfortunately! Try a more powerful machine. I don't have any exact advise about how to make it work better on your SBC off the top of my head to give you. I'd have to spend some significant time with your particular hardware and situation to look into it and see how we can accelerate or improve things. Unfortunately, that's not something I can do as part of this package's maintainer role. If you're interested in potentially some consulting to help, that might be something I can help with through [Open Navigation](https://www.opennav.org/).

**Comment by jesusramondovale** [comment]
Can't I change slam settings or something quickly to make it work? 

By the way, I don't think it's a CPU problem (my SBC has 4x1.80 GHz cores)  I reduced the map update interval and the CPU use time is now only on 50-60% but... the map isn't updated either.

**Comment by SteveMacenski** [comment]
See remark above. 

> I don't have any exact advise about how to make it work better on your SBC off the top of my head to give you.

There are users on Jetsons, RPi4's, etc. I can't know about your particular out of the ordinary SBC without digging very deep into it for you which I can't do without alot more information about your system/product/work. Unfortunately, you're a bit out of luck from a package maintainer's perspective.

**Comment by jesusramondovale** [comment]
It was a privileges problem. Odom node must be executed as root in order to communicate with the Portenta control board, so slam node also needs to be executed as root. If not, slam node can't receive the info of the odom node. 
Executed all nodes as root (inside DEBIX SBC) and everything worked fine, even with a 1 CM per pixel resolution. It is clear that it wasn't a CPU problem.

You can close this issue, now.
