### ISSUE TITLE
My parameters were reset as a result of the system update

### ISSUE THREAD

**Issue by hsynklceng** [SteveMacenski/slam_toolbox#644]
Hi,
I am using ros-melodic devel. I installed the package with apt to /opt/ros/melodic/share. I made changes to the parameters as a result of a lot of testing. After a system update today, all the changes I made were reset and the package returned to its original state.

How can i find my parameters? please help me!

**Comment by SteveMacenski** [comment]
Store you own param files, you should not be modifying files in opt/ros. That is unrecoverable. It is also not some special attribute of this package or even ros itself. Don’t manually modify binary’s files.
