### ISSUE TITLE
Multi robot environment not working

### ISSUE THREAD

**Issue by lliendo** [SteveMacenski/slam_toolbox#645]
**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 Galactic
  
#### Problem description

I'm trying to generate a single map using two robots. I'm not using real robots but a Webots environment. I've described with as much information as possible in this post in the Robotics Exchange site:

[Multi robot SLAM problem](https://robotics.stackexchange.com/questions/105228/multi-robot-slam-problem)

For the issue described above, today I've also tried to namespace the `/map` topic to `/mir_X/map` (e.g: `/mir_1/map`, `/mir_2/map`) with the hope of seeing two different maps (one for each robot in two different RViz) again with no luck. As per the post mentioned above again when I inspect the graphs they seem to be ok for one robot but wrong when two robots are spawned through launch files in _exactly_ the same way.

Is it possible that the slam toolbox at some point is reusing something or some value is hardcoded that makes this setup impossible to work? I've to the best of my knowledge tried everything related to namespacing topics, frames, etc again without success. I'm surprised that even the last test that I performed where I expect to have two completely different maps generated for each robot does not work.

#### Expected behavior

One single map generated from the information from two or more robots or alternatively two or more different maps produced for each namespace/robot.

#### Actual behavior

No maps are generated in any case.

Any insights as for why this happens much appreciated!

Thanks for your time,
Lucas.

**Comment by SteveMacenski** [comment]
Please don’t cross post with question sites
