### ISSUE TITLE
SLAM Toolbox with hilly terrains

### ISSUE THREAD

**Issue by mattiadutto** [SteveMacenski/slam_toolbox#684]
From what I can see on the code and based on what I saw online there is no possibility to use the SLAM Toolbox with hilly terrains or I am wrong? Because from what I understood, when the SLAM Toolbox adds a new scan just use the 2D coordinate of the scan.

So if I want to map a hilly terrain or a building with more than 1 floor and I also want to map the scale I have to use something that supports visual SLAM right?

Thanks

**Comment by SteveMacenski** [comment]
This is a 2D lidar slam, no, it is not appropriate where the environment cannot be modeled in 2D

**Comment by mattiadutto** [comment]
Thank you very much!
