### ISSUE TITLE
Ceres terminated on loop closure

### ISSUE THREAD

**Issue by cblesing** [SteveMacenski/slam_toolbox#690]
**Required Info:**

- Operating System:
 Ubuntu 20.04
- Installation type:
 cloned from git (branch noetic-devel)
- ROS Version
  ROS1
- Version or commit hash:
  - 
- Laser unit:
  Velodyne VLP16
  
#### Steps to reproduce issue
Start online_sync or online_async launch file. As soon as a loop closure is detected the ceres solver is terminated with 
`
process[slam_toolbox-1]: started with pid [2628272]
[ INFO] [1713860198.996655698]: Node using stack size 40000000
[ INFO] [1713860199.031781659]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[ INFO] [1713860199.031829711]: Using plugin solver_plugins::CeresSolver
Registering sensor: [Custom Described Lidar]
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0423 10:17:47.272751 2628291 solver.cc:507] Terminating: Invalid configuration. Solver::Options::num_linear_solver_threads = -1. Violated constraint: Solver::Options::num_linear_solver_threads > 0
[ WARN] [1713860267.272794065]: CeresSolver: Ceres could not find a usable solution to optimize.
[slam_toolbox-1] process has died [pid 2628272, exit code -11, cmd /opt/obelix/extended_ws/devel/lib/slam_toolbox/sync_slam_toolbox_node __name:=slam_toolbox __log:=/home/obelix/.ros/log/866fe4ca-0145-11ef-ba1f-f5ad4588eca1/slam_toolbox-1.log].
log file: /home/obelix/.ros/log/866fe4ca-0145-11ef-ba1f-f5ad4588eca1/slam_toolbox-1*.log
`
I am using the latest version of ceres. Any idea what causes this error? I used slam_toolbox for a long time and have never seen this.

Regards 
Christian

**Comment by SteveMacenski** [comment]
Use Ceres from the ROS distribution you're using - its versioned to the distribution's released versions of all dependencies (i.e. what ships with Ubuntu 20)
