### ISSUE TITLE
Map is overlapping and doesn't make loop_closure 

### ISSUE THREAD

**Issue by Zarqu0n** [SteveMacenski/slam_toolbox#692]
**Required Info:**

- Operating System:
Ubuntu 22.04
- Installation type:
  binaries
- ROS Version
  ROS2 Humble
- Version or commit hash:
 release version
- Laser unit:
 RP Lidar
  
#### Steps to reproduce issue
Doesn't make loop closure in big loops in default async node parameters.

#### Actual behavior
![Screenshot from 2024-04-26 09-49-03](https://github.com/SteveMacenski/slam_toolbox/assets/72468520/ff0130e7-8fec-40bf-a678-97836ea8c33c)
![Screenshot from 2024-04-26 10-00-39](https://github.com/SteveMacenski/slam_toolbox/assets/72468520/ea05cf31-b0df-4f1b-8de1-104ad14aaba5)

We mapped it on the map above and using the async mode with default parameters. It did not connect the pose graph nodes between the point where we started mapping and the point where we finished mapping. It made a small modification to the map but did not complete the loop closure. It did not connect the pose graph nodes between the point where we started mapping and the point where we finished mapping. It made a small modification to the map but did not complete the loop closure. For examples.

![Screenshot from 2024-04-26 09-49-18](https://github.com/SteveMacenski/slam_toolbox/assets/72468520/c9569cbb-1ad8-4948-871c-709ddad165bc)

![Screenshot from 2024-04-26 09-49-26](https://github.com/SteveMacenski/slam_toolbox/assets/72468520/15c6cbcf-606f-47a4-b4cb-7f48a857ed20)

![Screenshot from 2024-04-26 09-49-32](https://github.com/SteveMacenski/slam_toolbox/assets/72468520/725c9a60-c49b-4026-8a30-a7e172854e28)

Can you help me what to do in this case, which parameters I can tune or any other solution.

#### Additional information

- We are use the EKF with fusing wheel encoder and 6 DOF IMU. I have looked at other issues related to this incident. It is generally said to be related to the quality of the odometry. I think the odometry we use in my tests is of good quality.
- Map size 142 m (height) x 389 m (Width).
- If you would like a bag file to help me, you can contact me by e-mail.
Thank you in advance for your help.

**Comment by SteveMacenski** [comment]
Ask on ROS Answers, but this looks correct to me. Please let us know why you think the start and end nodes you point out should somehow be connected (and the session know that that's the "end" for that to be semantically meaningful)

**Comment by Zarqu0n** [comment]
We had manually pushed the robot around to map and explore the area. We started the robot from the same point and brought it back to that point, expecting it to perform a loop closure. However, it didn’t happen. I know the map is quite large and the small errors in our odometry accumulate over time and impact the results. Unfortunately, there isn’t a smaller loop available where we could expect to return to the starting point. I am looking into similar issues that have been opened and trying to gather information from them. Meanwhile, I am tuning parameters and researching what else I can do to test. I will continue to share my findings and methods here. I also tried a manual loop closure, but either I didn’t succeed or the integration isn’t complete yet.

**Comment by maladzenkau** [comment]
> We had manually pushed the robot around to map and explore the area. We started the robot from the same point and brought it back to that point, expecting it to perform a loop closure. However, it didn’t happen. I know the map is quite large and the small errors in our odometry accumulate over time and impact the results. Unfortunately, there isn’t a smaller loop available where we could expect to return to the starting point. I am looking into similar issues that have been opened and trying to gather information from them. Meanwhile, I am tuning parameters and researching what else I can do to test. I will continue to share my findings and methods here. I also tried a manual loop closure, but either I didn’t succeed or the integration isn’t complete yet.

Hi, @Zarqu0n. Do you have any update on this problem?
I have exactly the same case. Trying to fix it using GPS, but didn't succeed so far.
