### ISSUE TITLE
LaserScan mismatch

### ISSUE THREAD

**Issue by sesem738** [SteveMacenski/slam_toolbox#702]
Operating System:
 - Ubuntu 20.04
Installation type:
 - binaries
ROS Version:
 - ROS1 Noetic
Version or commit hash:
 - noetic-devel
Laser unit:
 - RPLidar A3

**Steps to reproduce issue**
launch rplidarNode and launch online_sync_launch.py

**Expected behavior**
map received

**Actual behavior**
LaserRangeScan contains 1947 range readings, expected 1946

and no map received on rivz

**Comment by SteveMacenski** [comment]
See https://github.com/SteveMacenski/slam_toolbox/issues/430
