### ISSUE TITLE
Facing error while running colcon test

### ISSUE THREAD

**Issue by ShivaHari009** [SteveMacenski/slam_toolbox#708]
Hi, I just cloned this slam tool-box into my docker container which my image is (ros:eloquent-ros-base-bionic) and i built this package into my workspace. After that i have ran colcon test command then i faced this issue which is shown in the image,
![Screenshot from 2024-06-17 23-29-17](https://github.com/SteveMacenski/slam_toolbox/assets/150611687/dc5d48f6-d4be-4564-97f6-3c11439af8c6)

**Comment by SteveMacenski** [comment]
Eloquent has no support anymore and is EOL
