### ISSUE TITLE
Support for ROS2 Jazzy Jalisco

### ISSUE THREAD

**Issue by k12onoss** [SteveMacenski/slam_toolbox#710]
Now that ROS2 Jazzy has been out for around a month, is there any ETA for ros-jazzy-slam-toolbox package?

**Comment by SteveMacenski** [comment]
There's a dependency on Nav2, which is currently in process. The `ros2` branch works with Jazzy though! You just need to compile it from source :smile: 

I hope to have this released in July

**Comment by k12onoss** [comment]
I see, thanks for the prompt reply!

I'll keep this issue open for reference until there's an official release, if that's okay.

**Comment by k12onoss** [comment]
It seems the release is out. Thanks.
