### ISSUE TITLE
#714 breaks the build

### ISSUE THREAD

**Issue by james-ward** [SteveMacenski/slam_toolbox#715]
PR #714 refers to member variable `node_` which does not exist in the class.

**Comment by SteveMacenski** [comment]
Ugh. Please submit a PR and I can merge

**Comment by CihatAltiparmak** [comment]
Hello @SteveMacenski , i have a PR(https://github.com/SteveMacenski/slam_toolbox/pull/718) to fix this problem. It's ready to your service.

**Comment by SteveMacenski** [comment]
Merged!
