### ISSUE TITLE
Load Map

### ISSUE THREAD

**Issue by amit-z** [SteveMacenski/slam_toolbox#719]
I am using slam toolbox with ROS2 - foxy. I have seen that there is a feature to load an existing map, by uncommenting the following params:

```
    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    #map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true
```
    
However, I have not seen an example for it. 
Is this feature working? 
What is the way to use it, i.e what is the default directory and how should I reference the map?
What should be the map type (pgm/yaml)?
Is there an relevant example?

**Comment by SteveMacenski** [comment]
Ask on robotics stack exchange, but I don't have any reason to think its not working unless you're reporting that its not working.
