### ISSUE TITLE
Motion compensation to undistort raw LIDAR readings

### ISSUE THREAD

**Issue by billkotsias** [SteveMacenski/slam_toolbox#723]
#### Feature description
When robot is moving during mapping, LIDAR readings produce a distorted view of its surroundings. AFAICS, slam_toolbox compensates for all scan poses but doesn't do motion compensation within a LIDAR scan.

#### Implementation considerations
There are already motion compensation filters, however they produce a `PointCloud`. The [default scan message](https://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/LaserScan.html) that **slam_toolbox** expects is very limited, as it can only represent rays that have the same angle between them, which is **not** the case when doing motion compensation.

IMHO it would be very robust to be able to feed **slam_toolbox** with a pre-compensated LIDAR PointCloud instead of `LaserScan`.

**Comment by billkotsias** [comment]
![image](https://github.com/user-attachments/assets/888bca1f-22c6-42cb-bb49-e96048fa862b)

- red distorted
- white compensated

**Comment by SteveMacenski** [comment]
You can feed in your undistorted scan into slam toolbox using a scan undistortion node between the raw sensor data and the slam method

**Comment by billkotsias** [comment]
@SteveMacenski I'm a newbie to SLMT... Could you please point me to some guide/code on how to insert such a node between raw data and SLAM method?

Is there a point in code where raw LIDAR rays are converted to 2D points, so that I can add my filter there?

**Comment by SteveMacenski** [comment]
1. In your launch file, remap the input topic to the motion compensator to your sensor & output topic to some intermediate topic X
2. In your launch file, remap the input topic for slam toolbox to X (or use the provided parameter in the parameter file)
3. It works!

**Comment by billkotsias** [comment]
Thank you for taking the time!
I'm afraid it won't be that simple though because - like I said in original post :
> There are already motion compensation filters, however they produce a **_PointCloud_**. The [default scan message](https://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/LaserScan.html) that **slam_toolbox expects** is very limited, as _it can only represent rays that have the same angle between them, which is not the case when doing motion compensation_.

In other words, motion compensator filter produces points that no longer lie on rays of equidistant angle.

So I guess I will need to adapt the SLMT lidar message interpreter.
